// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttendanceMonthsColumns holds the columns for the "attendance_months" table.
	AttendanceMonthsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "student_id", Type: field.TypeInt},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "year", Type: field.TypeInt},
		{Name: "month", Type: field.TypeInt},
		{Name: "lessons_count", Type: field.TypeFloat64, Default: 0},
	}
	// AttendanceMonthsTable holds the schema information for the "attendance_months" table.
	AttendanceMonthsTable = &schema.Table{
		Name:       "attendance_months",
		Columns:    AttendanceMonthsColumns,
		PrimaryKey: []*schema.Column{AttendanceMonthsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "attendancemonth_student_id_course_id_year_month",
				Unique:  true,
				Columns: []*schema.Column{AttendanceMonthsColumns[1], AttendanceMonthsColumns[2], AttendanceMonthsColumns[3], AttendanceMonthsColumns[4]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor_label", Type: field.TypeString, Default: "system"},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "entity_id", Type: field.TypeInt, Nullable: true},
		{Name: "action", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString},
		{Name: "before_json", Type: field.TypeString, Default: ""},
		{Name: "after_json", Type: field.TypeString, Default: ""},
		{Name: "student_id", Type: field.TypeInt, Nullable: true},
		{Name: "invoice_id", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "actor_user_id", Type: field.TypeInt, Nullable: true},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_logs_users_audit_logs",
				Columns:    []*schema.Column{AuditLogsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[10]},
			},
			{
				Name:    "auditlog_actor_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[11], AuditLogsColumns[10]},
			},
			{
				Name:    "auditlog_entity_type_entity_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[2], AuditLogsColumns[3]},
			},
			{
				Name:    "auditlog_action_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[4], AuditLogsColumns[10]},
			},
			{
				Name:    "auditlog_student_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[8], AuditLogsColumns[10]},
			},
			{
				Name:    "auditlog_invoice_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[9], AuditLogsColumns[10]},
			},
		},
	}
	// CoursesColumns holds the columns for the "courses" table.
	CoursesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "name", Type: field.TypeString},
		{Name: "teacher_name", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"group", "individual"}},
		{Name: "lesson_price", Type: field.TypeFloat64, Default: 0},
		{Name: "subscription_price", Type: field.TypeFloat64, Default: 0},
		{Name: "lesson_price_cents", Type: field.TypeInt64, Default: 0},
		{Name: "subscription_price_cents", Type: field.TypeInt64, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "teacher_id", Type: field.TypeInt, Nullable: true},
	}
	// CoursesTable holds the schema information for the "courses" table.
	CoursesTable = &schema.Table{
		Name:       "courses",
		Columns:    CoursesColumns,
		PrimaryKey: []*schema.Column{CoursesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "courses_teachers_courses",
				Columns:    []*schema.Column{CoursesColumns[10]},
				RefColumns: []*schema.Column{TeachersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CourseMonthStatsColumns holds the columns for the "course_month_stats" table.
	CourseMonthStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "year", Type: field.TypeInt},
		{Name: "month", Type: field.TypeInt},
		{Name: "subscription_lessons_held", Type: field.TypeFloat64, Default: 0},
		{Name: "course_id", Type: field.TypeInt},
	}
	// CourseMonthStatsTable holds the schema information for the "course_month_stats" table.
	CourseMonthStatsTable = &schema.Table{
		Name:       "course_month_stats",
		Columns:    CourseMonthStatsColumns,
		PrimaryKey: []*schema.Column{CourseMonthStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "course_month_stats_courses_month_stats",
				Columns:    []*schema.Column{CourseMonthStatsColumns[4]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "coursemonthstat_course_id_year_month",
				Unique:  true,
				Columns: []*schema.Column{CourseMonthStatsColumns[4], CourseMonthStatsColumns[1], CourseMonthStatsColumns[2]},
			},
		},
	}
	// EnrollmentsColumns holds the columns for the "enrollments" table.
	EnrollmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "billing_mode", Type: field.TypeEnum, Enums: []string{"subscription", "per_lesson"}},
		{Name: "charge_materials", Type: field.TypeBool, Default: true},
		{Name: "discount_pct", Type: field.TypeFloat64, Default: 0},
		{Name: "subscription_lesson_price_cents", Type: field.TypeInt64, Default: -1},
		{Name: "note", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "course_id", Type: field.TypeInt},
		{Name: "student_id", Type: field.TypeInt},
	}
	// EnrollmentsTable holds the schema information for the "enrollments" table.
	EnrollmentsTable = &schema.Table{
		Name:       "enrollments",
		Columns:    EnrollmentsColumns,
		PrimaryKey: []*schema.Column{EnrollmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "enrollments_courses_enrollments",
				Columns:    []*schema.Column{EnrollmentsColumns[9]},
				RefColumns: []*schema.Column{CoursesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "enrollments_students_enrollments",
				Columns:    []*schema.Column{EnrollmentsColumns[10]},
				RefColumns: []*schema.Column{StudentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "enrollment_student_id_course_id",
				Unique:  true,
				Columns: []*schema.Column{EnrollmentsColumns[10], EnrollmentsColumns[9]},
			},
		},
	}
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "period_year", Type: field.TypeInt},
		{Name: "period_month", Type: field.TypeInt},
		{Name: "total_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "total_amount_cents", Type: field.TypeInt64, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "issued", "paid", "canceled"}, Default: "draft"},
		{Name: "number", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "student_id", Type: field.TypeInt},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoices_students_invoices",
				Columns:    []*schema.Column{InvoicesColumns[10]},
				RefColumns: []*schema.Column{StudentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invoice_student_id_period_year_period_month",
				Unique:  true,
				Columns: []*schema.Column{InvoicesColumns[10], InvoicesColumns[2], InvoicesColumns[3]},
			},
		},
	}
	// InvoiceLinesColumns holds the columns for the "invoice_lines" table.
	InvoiceLinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString},
		{Name: "qty", Type: field.TypeFloat64},
		{Name: "unit_price", Type: field.TypeFloat64, Default: 0},
		{Name: "amount", Type: field.TypeFloat64, Default: 0},
		{Name: "unit_price_cents", Type: field.TypeInt64, Default: 0},
		{Name: "amount_cents", Type: field.TypeInt64, Default: 0},
		{Name: "enrollment_id", Type: field.TypeInt},
		{Name: "invoice_id", Type: field.TypeInt},
	}
	// InvoiceLinesTable holds the schema information for the "invoice_lines" table.
	InvoiceLinesTable = &schema.Table{
		Name:       "invoice_lines",
		Columns:    InvoiceLinesColumns,
		PrimaryKey: []*schema.Column{InvoiceLinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoice_lines_enrollments_invoice_lines",
				Columns:    []*schema.Column{InvoiceLinesColumns[7]},
				RefColumns: []*schema.Column{EnrollmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "invoice_lines_invoices_lines",
				Columns:    []*schema.Column{InvoiceLinesColumns[8]},
				RefColumns: []*schema.Column{InvoicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invoiceline_invoice_id",
				Unique:  false,
				Columns: []*schema.Column{InvoiceLinesColumns[8]},
			},
			{
				Name:    "invoiceline_enrollment_id",
				Unique:  false,
				Columns: []*schema.Column{InvoiceLinesColumns[7]},
			},
		},
	}
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "paid_at", Type: field.TypeTime},
		{Name: "amount", Type: field.TypeFloat64, Default: 0},
		{Name: "amount_cents", Type: field.TypeInt64, Default: 0},
		{Name: "method", Type: field.TypeEnum, Enums: []string{"cash", "bank"}},
		{Name: "note", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "invoice_id", Type: field.TypeInt, Nullable: true},
		{Name: "student_id", Type: field.TypeInt},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payments_invoices_payments",
				Columns:    []*schema.Column{PaymentsColumns[7]},
				RefColumns: []*schema.Column{InvoicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "payments_students_payments",
				Columns:    []*schema.Column{PaymentsColumns[8]},
				RefColumns: []*schema.Column{StudentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "payment_student_id_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[8], PaymentsColumns[1]},
			},
			{
				Name:    "payment_invoice_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[7]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "singleton_id", Type: field.TypeInt, Unique: true},
		{Name: "org_name", Type: field.TypeString, Default: ""},
		{Name: "address", Type: field.TypeString, Default: ""},
		{Name: "invoice_prefix", Type: field.TypeString, Default: "LS"},
		{Name: "next_seq", Type: field.TypeInt, Default: 1},
		{Name: "invoice_day_of_month", Type: field.TypeInt, Default: 1},
		{Name: "currency", Type: field.TypeString, Default: "EUR"},
		{Name: "locale", Type: field.TypeString, Default: "en-US"},
		{Name: "invoice_email_subject_template", Type: field.TypeString, Default: ""},
		{Name: "invoice_email_body_template", Type: field.TypeString, Default: ""},
		{Name: "invoice_reply_to", Type: field.TypeString, Default: ""},
		{Name: "money_cents_migrated", Type: field.TypeBool, Default: false},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// StudentsColumns holds the columns for the "students" table.
	StudentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "full_name", Type: field.TypeString},
		{Name: "personal_code", Type: field.TypeString, Default: ""},
		{Name: "phone", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "note", Type: field.TypeString, Default: ""},
		{Name: "is_minor", Type: field.TypeBool, Default: false},
		{Name: "payer_name", Type: field.TypeString, Default: ""},
		{Name: "payer_role", Type: field.TypeString, Default: ""},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// StudentsTable holds the schema information for the "students" table.
	StudentsTable = &schema.Table{
		Name:       "students",
		Columns:    StudentsColumns,
		PrimaryKey: []*schema.Column{StudentsColumns[0]},
	}
	// TeachersColumns holds the columns for the "teachers" table.
	TeachersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// TeachersTable holds the schema information for the "teachers" table.
	TeachersTable = &schema.Table{
		Name:       "teachers",
		Columns:    TeachersColumns,
		PrimaryKey: []*schema.Column{TeachersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "admin"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "ui_locale", Type: field.TypeString, Default: "lv-LV"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebSessionsColumns holds the columns for the "web_sessions" table.
	WebSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// WebSessionsTable holds the schema information for the "web_sessions" table.
	WebSessionsTable = &schema.Table{
		Name:       "web_sessions",
		Columns:    WebSessionsColumns,
		PrimaryKey: []*schema.Column{WebSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "web_sessions_users_sessions",
				Columns:    []*schema.Column{WebSessionsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttendanceMonthsTable,
		AuditLogsTable,
		CoursesTable,
		CourseMonthStatsTable,
		EnrollmentsTable,
		InvoicesTable,
		InvoiceLinesTable,
		PaymentsTable,
		SettingsTable,
		StudentsTable,
		TeachersTable,
		UsersTable,
		WebSessionsTable,
	}
)

func init() {
	AuditLogsTable.ForeignKeys[0].RefTable = UsersTable
	CoursesTable.ForeignKeys[0].RefTable = TeachersTable
	CourseMonthStatsTable.ForeignKeys[0].RefTable = CoursesTable
	EnrollmentsTable.ForeignKeys[0].RefTable = CoursesTable
	EnrollmentsTable.ForeignKeys[1].RefTable = StudentsTable
	InvoicesTable.ForeignKeys[0].RefTable = StudentsTable
	InvoiceLinesTable.ForeignKeys[0].RefTable = EnrollmentsTable
	InvoiceLinesTable.ForeignKeys[1].RefTable = InvoicesTable
	PaymentsTable.ForeignKeys[0].RefTable = InvoicesTable
	PaymentsTable.ForeignKeys[1].RefTable = StudentsTable
	WebSessionsTable.ForeignKeys[0].RefTable = UsersTable
}
