// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"langschool/ent/attendancemonth"
	"langschool/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttendanceMonthDelete is the builder for deleting a AttendanceMonth entity.
type AttendanceMonthDelete struct {
	config
	hooks    []Hook
	mutation *AttendanceMonthMutation
}

// Where appends a list predicates to the AttendanceMonthDelete builder.
func (_d *AttendanceMonthDelete) Where(ps ...predicate.AttendanceMonth) *AttendanceMonthDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AttendanceMonthDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AttendanceMonthDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AttendanceMonthDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attendancemonth.Table, sqlgraph.NewFieldSpec(attendancemonth.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AttendanceMonthDeleteOne is the builder for deleting a single AttendanceMonth entity.
type AttendanceMonthDeleteOne struct {
	_d *AttendanceMonthDelete
}

// Where appends a list predicates to the AttendanceMonthDelete builder.
func (_d *AttendanceMonthDeleteOne) Where(ps ...predicate.AttendanceMonth) *AttendanceMonthDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AttendanceMonthDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attendancemonth.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AttendanceMonthDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
