// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"langschool/ent/auditlog"
	"langschool/ent/predicate"
	"langschool/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *AuditLogUpdate) SetActorUserID(v int) *AuditLogUpdate {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorUserID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *AuditLogUpdate) ClearActorUserID() *AuditLogUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetActorLabel sets the "actor_label" field.
func (_u *AuditLogUpdate) SetActorLabel(v string) *AuditLogUpdate {
	_u.mutation.SetActorLabel(v)
	return _u
}

// SetNillableActorLabel sets the "actor_label" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorLabel(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorLabel(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *AuditLogUpdate) SetEntityType(v string) *AuditLogUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableEntityType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *AuditLogUpdate) SetEntityID(v int) *AuditLogUpdate {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableEntityID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *AuditLogUpdate) AddEntityID(v int) *AuditLogUpdate {
	_u.mutation.AddEntityID(v)
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *AuditLogUpdate) ClearEntityID() *AuditLogUpdate {
	_u.mutation.ClearEntityID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *AuditLogUpdate) SetSummary(v string) *AuditLogUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableSummary(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetBeforeJSON sets the "before_json" field.
func (_u *AuditLogUpdate) SetBeforeJSON(v string) *AuditLogUpdate {
	_u.mutation.SetBeforeJSON(v)
	return _u
}

// SetNillableBeforeJSON sets the "before_json" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableBeforeJSON(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetBeforeJSON(*v)
	}
	return _u
}

// SetAfterJSON sets the "after_json" field.
func (_u *AuditLogUpdate) SetAfterJSON(v string) *AuditLogUpdate {
	_u.mutation.SetAfterJSON(v)
	return _u
}

// SetNillableAfterJSON sets the "after_json" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAfterJSON(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAfterJSON(*v)
	}
	return _u
}

// SetStudentID sets the "student_id" field.
func (_u *AuditLogUpdate) SetStudentID(v int) *AuditLogUpdate {
	_u.mutation.ResetStudentID()
	_u.mutation.SetStudentID(v)
	return _u
}

// SetNillableStudentID sets the "student_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableStudentID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetStudentID(*v)
	}
	return _u
}

// AddStudentID adds value to the "student_id" field.
func (_u *AuditLogUpdate) AddStudentID(v int) *AuditLogUpdate {
	_u.mutation.AddStudentID(v)
	return _u
}

// ClearStudentID clears the value of the "student_id" field.
func (_u *AuditLogUpdate) ClearStudentID() *AuditLogUpdate {
	_u.mutation.ClearStudentID()
	return _u
}

// SetInvoiceID sets the "invoice_id" field.
func (_u *AuditLogUpdate) SetInvoiceID(v int) *AuditLogUpdate {
	_u.mutation.ResetInvoiceID()
	_u.mutation.SetInvoiceID(v)
	return _u
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableInvoiceID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetInvoiceID(*v)
	}
	return _u
}

// AddInvoiceID adds value to the "invoice_id" field.
func (_u *AuditLogUpdate) AddInvoiceID(v int) *AuditLogUpdate {
	_u.mutation.AddInvoiceID(v)
	return _u
}

// ClearInvoiceID clears the value of the "invoice_id" field.
func (_u *AuditLogUpdate) ClearInvoiceID() *AuditLogUpdate {
	_u.mutation.ClearInvoiceID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdate) SetCreatedAt(v time.Time) *AuditLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableCreatedAt(v *time.Time) *AuditLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_u *AuditLogUpdate) SetActorUser(v *User) *AuditLogUpdate {
	return _u.SetActorUserID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearActorUser clears the "actor_user" edge to the User entity.
func (_u *AuditLogUpdate) ClearActorUser() *AuditLogUpdate {
	_u.mutation.ClearActorUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorLabel(); ok {
		_spec.SetField(auditlog.FieldActorLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(auditlog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(auditlog.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(auditlog.FieldEntityID, field.TypeInt, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(auditlog.FieldEntityID, field.TypeInt)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(auditlog.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeJSON(); ok {
		_spec.SetField(auditlog.FieldBeforeJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.AfterJSON(); ok {
		_spec.SetField(auditlog.FieldAfterJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.StudentID(); ok {
		_spec.SetField(auditlog.FieldStudentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStudentID(); ok {
		_spec.AddField(auditlog.FieldStudentID, field.TypeInt, value)
	}
	if _u.mutation.StudentIDCleared() {
		_spec.ClearField(auditlog.FieldStudentID, field.TypeInt)
	}
	if value, ok := _u.mutation.InvoiceID(); ok {
		_spec.SetField(auditlog.FieldInvoiceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInvoiceID(); ok {
		_spec.AddField(auditlog.FieldInvoiceID, field.TypeInt, value)
	}
	if _u.mutation.InvoiceIDCleared() {
		_spec.ClearField(auditlog.FieldInvoiceID, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ActorUserTable,
			Columns: []string{auditlog.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ActorUserTable,
			Columns: []string{auditlog.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *AuditLogUpdateOne) SetActorUserID(v int) *AuditLogUpdateOne {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorUserID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *AuditLogUpdateOne) ClearActorUserID() *AuditLogUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetActorLabel sets the "actor_label" field.
func (_u *AuditLogUpdateOne) SetActorLabel(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorLabel(v)
	return _u
}

// SetNillableActorLabel sets the "actor_label" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorLabel(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorLabel(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *AuditLogUpdateOne) SetEntityType(v string) *AuditLogUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableEntityType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *AuditLogUpdateOne) SetEntityID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetEntityID()
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableEntityID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// AddEntityID adds value to the "entity_id" field.
func (_u *AuditLogUpdateOne) AddEntityID(v int) *AuditLogUpdateOne {
	_u.mutation.AddEntityID(v)
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *AuditLogUpdateOne) ClearEntityID() *AuditLogUpdateOne {
	_u.mutation.ClearEntityID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *AuditLogUpdateOne) SetSummary(v string) *AuditLogUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableSummary(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetBeforeJSON sets the "before_json" field.
func (_u *AuditLogUpdateOne) SetBeforeJSON(v string) *AuditLogUpdateOne {
	_u.mutation.SetBeforeJSON(v)
	return _u
}

// SetNillableBeforeJSON sets the "before_json" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableBeforeJSON(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetBeforeJSON(*v)
	}
	return _u
}

// SetAfterJSON sets the "after_json" field.
func (_u *AuditLogUpdateOne) SetAfterJSON(v string) *AuditLogUpdateOne {
	_u.mutation.SetAfterJSON(v)
	return _u
}

// SetNillableAfterJSON sets the "after_json" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAfterJSON(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAfterJSON(*v)
	}
	return _u
}

// SetStudentID sets the "student_id" field.
func (_u *AuditLogUpdateOne) SetStudentID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetStudentID()
	_u.mutation.SetStudentID(v)
	return _u
}

// SetNillableStudentID sets the "student_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableStudentID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetStudentID(*v)
	}
	return _u
}

// AddStudentID adds value to the "student_id" field.
func (_u *AuditLogUpdateOne) AddStudentID(v int) *AuditLogUpdateOne {
	_u.mutation.AddStudentID(v)
	return _u
}

// ClearStudentID clears the value of the "student_id" field.
func (_u *AuditLogUpdateOne) ClearStudentID() *AuditLogUpdateOne {
	_u.mutation.ClearStudentID()
	return _u
}

// SetInvoiceID sets the "invoice_id" field.
func (_u *AuditLogUpdateOne) SetInvoiceID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetInvoiceID()
	_u.mutation.SetInvoiceID(v)
	return _u
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableInvoiceID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetInvoiceID(*v)
	}
	return _u
}

// AddInvoiceID adds value to the "invoice_id" field.
func (_u *AuditLogUpdateOne) AddInvoiceID(v int) *AuditLogUpdateOne {
	_u.mutation.AddInvoiceID(v)
	return _u
}

// ClearInvoiceID clears the value of the "invoice_id" field.
func (_u *AuditLogUpdateOne) ClearInvoiceID() *AuditLogUpdateOne {
	_u.mutation.ClearInvoiceID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdateOne) SetCreatedAt(v time.Time) *AuditLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableCreatedAt(v *time.Time) *AuditLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetActorUser sets the "actor_user" edge to the User entity.
func (_u *AuditLogUpdateOne) SetActorUser(v *User) *AuditLogUpdateOne {
	return _u.SetActorUserID(v.ID)
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// ClearActorUser clears the "actor_user" edge to the User entity.
func (_u *AuditLogUpdateOne) ClearActorUser() *AuditLogUpdateOne {
	_u.mutation.ClearActorUser()
	return _u
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorLabel(); ok {
		_spec.SetField(auditlog.FieldActorLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(auditlog.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(auditlog.FieldEntityID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntityID(); ok {
		_spec.AddField(auditlog.FieldEntityID, field.TypeInt, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(auditlog.FieldEntityID, field.TypeInt)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(auditlog.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeJSON(); ok {
		_spec.SetField(auditlog.FieldBeforeJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.AfterJSON(); ok {
		_spec.SetField(auditlog.FieldAfterJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.StudentID(); ok {
		_spec.SetField(auditlog.FieldStudentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStudentID(); ok {
		_spec.AddField(auditlog.FieldStudentID, field.TypeInt, value)
	}
	if _u.mutation.StudentIDCleared() {
		_spec.ClearField(auditlog.FieldStudentID, field.TypeInt)
	}
	if value, ok := _u.mutation.InvoiceID(); ok {
		_spec.SetField(auditlog.FieldInvoiceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInvoiceID(); ok {
		_spec.AddField(auditlog.FieldInvoiceID, field.TypeInt, value)
	}
	if _u.mutation.InvoiceIDCleared() {
		_spec.ClearField(auditlog.FieldInvoiceID, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActorUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ActorUserTable,
			Columns: []string{auditlog.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auditlog.ActorUserTable,
			Columns: []string{auditlog.ActorUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
