// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"langschool/ent/migrate"

	"langschool/ent/attendancemonth"
	"langschool/ent/course"
	"langschool/ent/enrollment"
	"langschool/ent/invoice"
	"langschool/ent/invoiceline"
	"langschool/ent/priceoverride"
	"langschool/ent/settings"
	"langschool/ent/student"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AttendanceMonth is the client for interacting with the AttendanceMonth builders.
	AttendanceMonth *AttendanceMonthClient
	// Course is the client for interacting with the Course builders.
	Course *CourseClient
	// Enrollment is the client for interacting with the Enrollment builders.
	Enrollment *EnrollmentClient
	// Invoice is the client for interacting with the Invoice builders.
	Invoice *InvoiceClient
	// InvoiceLine is the client for interacting with the InvoiceLine builders.
	InvoiceLine *InvoiceLineClient
	// PriceOverride is the client for interacting with the PriceOverride builders.
	PriceOverride *PriceOverrideClient
	// Settings is the client for interacting with the Settings builders.
	Settings *SettingsClient
	// Student is the client for interacting with the Student builders.
	Student *StudentClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AttendanceMonth = NewAttendanceMonthClient(c.config)
	c.Course = NewCourseClient(c.config)
	c.Enrollment = NewEnrollmentClient(c.config)
	c.Invoice = NewInvoiceClient(c.config)
	c.InvoiceLine = NewInvoiceLineClient(c.config)
	c.PriceOverride = NewPriceOverrideClient(c.config)
	c.Settings = NewSettingsClient(c.config)
	c.Student = NewStudentClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		AttendanceMonth: NewAttendanceMonthClient(cfg),
		Course:          NewCourseClient(cfg),
		Enrollment:      NewEnrollmentClient(cfg),
		Invoice:         NewInvoiceClient(cfg),
		InvoiceLine:     NewInvoiceLineClient(cfg),
		PriceOverride:   NewPriceOverrideClient(cfg),
		Settings:        NewSettingsClient(cfg),
		Student:         NewStudentClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		AttendanceMonth: NewAttendanceMonthClient(cfg),
		Course:          NewCourseClient(cfg),
		Enrollment:      NewEnrollmentClient(cfg),
		Invoice:         NewInvoiceClient(cfg),
		InvoiceLine:     NewInvoiceLineClient(cfg),
		PriceOverride:   NewPriceOverrideClient(cfg),
		Settings:        NewSettingsClient(cfg),
		Student:         NewStudentClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AttendanceMonth.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AttendanceMonth, c.Course, c.Enrollment, c.Invoice, c.InvoiceLine,
		c.PriceOverride, c.Settings, c.Student,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AttendanceMonth, c.Course, c.Enrollment, c.Invoice, c.InvoiceLine,
		c.PriceOverride, c.Settings, c.Student,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AttendanceMonthMutation:
		return c.AttendanceMonth.mutate(ctx, m)
	case *CourseMutation:
		return c.Course.mutate(ctx, m)
	case *EnrollmentMutation:
		return c.Enrollment.mutate(ctx, m)
	case *InvoiceMutation:
		return c.Invoice.mutate(ctx, m)
	case *InvoiceLineMutation:
		return c.InvoiceLine.mutate(ctx, m)
	case *PriceOverrideMutation:
		return c.PriceOverride.mutate(ctx, m)
	case *SettingsMutation:
		return c.Settings.mutate(ctx, m)
	case *StudentMutation:
		return c.Student.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AttendanceMonthClient is a client for the AttendanceMonth schema.
type AttendanceMonthClient struct {
	config
}

// NewAttendanceMonthClient returns a client for the AttendanceMonth from the given config.
func NewAttendanceMonthClient(c config) *AttendanceMonthClient {
	return &AttendanceMonthClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attendancemonth.Hooks(f(g(h())))`.
func (c *AttendanceMonthClient) Use(hooks ...Hook) {
	c.hooks.AttendanceMonth = append(c.hooks.AttendanceMonth, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attendancemonth.Intercept(f(g(h())))`.
func (c *AttendanceMonthClient) Intercept(interceptors ...Interceptor) {
	c.inters.AttendanceMonth = append(c.inters.AttendanceMonth, interceptors...)
}

// Create returns a builder for creating a AttendanceMonth entity.
func (c *AttendanceMonthClient) Create() *AttendanceMonthCreate {
	mutation := newAttendanceMonthMutation(c.config, OpCreate)
	return &AttendanceMonthCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AttendanceMonth entities.
func (c *AttendanceMonthClient) CreateBulk(builders ...*AttendanceMonthCreate) *AttendanceMonthCreateBulk {
	return &AttendanceMonthCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttendanceMonthClient) MapCreateBulk(slice any, setFunc func(*AttendanceMonthCreate, int)) *AttendanceMonthCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttendanceMonthCreateBulk{err: fmt.Errorf("calling to AttendanceMonthClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttendanceMonthCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttendanceMonthCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AttendanceMonth.
func (c *AttendanceMonthClient) Update() *AttendanceMonthUpdate {
	mutation := newAttendanceMonthMutation(c.config, OpUpdate)
	return &AttendanceMonthUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttendanceMonthClient) UpdateOne(_m *AttendanceMonth) *AttendanceMonthUpdateOne {
	mutation := newAttendanceMonthMutation(c.config, OpUpdateOne, withAttendanceMonth(_m))
	return &AttendanceMonthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttendanceMonthClient) UpdateOneID(id int) *AttendanceMonthUpdateOne {
	mutation := newAttendanceMonthMutation(c.config, OpUpdateOne, withAttendanceMonthID(id))
	return &AttendanceMonthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AttendanceMonth.
func (c *AttendanceMonthClient) Delete() *AttendanceMonthDelete {
	mutation := newAttendanceMonthMutation(c.config, OpDelete)
	return &AttendanceMonthDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttendanceMonthClient) DeleteOne(_m *AttendanceMonth) *AttendanceMonthDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttendanceMonthClient) DeleteOneID(id int) *AttendanceMonthDeleteOne {
	builder := c.Delete().Where(attendancemonth.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttendanceMonthDeleteOne{builder}
}

// Query returns a query builder for AttendanceMonth.
func (c *AttendanceMonthClient) Query() *AttendanceMonthQuery {
	return &AttendanceMonthQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttendanceMonth},
		inters: c.Interceptors(),
	}
}

// Get returns a AttendanceMonth entity by its id.
func (c *AttendanceMonthClient) Get(ctx context.Context, id int) (*AttendanceMonth, error) {
	return c.Query().Where(attendancemonth.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttendanceMonthClient) GetX(ctx context.Context, id int) *AttendanceMonth {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AttendanceMonthClient) Hooks() []Hook {
	return c.hooks.AttendanceMonth
}

// Interceptors returns the client interceptors.
func (c *AttendanceMonthClient) Interceptors() []Interceptor {
	return c.inters.AttendanceMonth
}

func (c *AttendanceMonthClient) mutate(ctx context.Context, m *AttendanceMonthMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttendanceMonthCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttendanceMonthUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttendanceMonthUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttendanceMonthDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AttendanceMonth mutation op: %q", m.Op())
	}
}

// CourseClient is a client for the Course schema.
type CourseClient struct {
	config
}

// NewCourseClient returns a client for the Course from the given config.
func NewCourseClient(c config) *CourseClient {
	return &CourseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `course.Hooks(f(g(h())))`.
func (c *CourseClient) Use(hooks ...Hook) {
	c.hooks.Course = append(c.hooks.Course, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `course.Intercept(f(g(h())))`.
func (c *CourseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Course = append(c.inters.Course, interceptors...)
}

// Create returns a builder for creating a Course entity.
func (c *CourseClient) Create() *CourseCreate {
	mutation := newCourseMutation(c.config, OpCreate)
	return &CourseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Course entities.
func (c *CourseClient) CreateBulk(builders ...*CourseCreate) *CourseCreateBulk {
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CourseClient) MapCreateBulk(slice any, setFunc func(*CourseCreate, int)) *CourseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CourseCreateBulk{err: fmt.Errorf("calling to CourseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CourseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Course.
func (c *CourseClient) Update() *CourseUpdate {
	mutation := newCourseMutation(c.config, OpUpdate)
	return &CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseClient) UpdateOne(_m *Course) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourse(_m))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseClient) UpdateOneID(id int) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourseID(id))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Course.
func (c *CourseClient) Delete() *CourseDelete {
	mutation := newCourseMutation(c.config, OpDelete)
	return &CourseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseClient) DeleteOne(_m *Course) *CourseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CourseClient) DeleteOneID(id int) *CourseDeleteOne {
	builder := c.Delete().Where(course.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseDeleteOne{builder}
}

// Query returns a query builder for Course.
func (c *CourseClient) Query() *CourseQuery {
	return &CourseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCourse},
		inters: c.Interceptors(),
	}
}

// Get returns a Course entity by its id.
func (c *CourseClient) Get(ctx context.Context, id int) (*Course, error) {
	return c.Query().Where(course.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseClient) GetX(ctx context.Context, id int) *Course {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEnrollments queries the enrollments edge of a Course.
func (c *CourseClient) QueryEnrollments(_m *Course) *EnrollmentQuery {
	query := (&EnrollmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(enrollment.Table, enrollment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.EnrollmentsTable, course.EnrollmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseClient) Hooks() []Hook {
	return c.hooks.Course
}

// Interceptors returns the client interceptors.
func (c *CourseClient) Interceptors() []Interceptor {
	return c.inters.Course
}

func (c *CourseClient) mutate(ctx context.Context, m *CourseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CourseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CourseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Course mutation op: %q", m.Op())
	}
}

// EnrollmentClient is a client for the Enrollment schema.
type EnrollmentClient struct {
	config
}

// NewEnrollmentClient returns a client for the Enrollment from the given config.
func NewEnrollmentClient(c config) *EnrollmentClient {
	return &EnrollmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `enrollment.Hooks(f(g(h())))`.
func (c *EnrollmentClient) Use(hooks ...Hook) {
	c.hooks.Enrollment = append(c.hooks.Enrollment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `enrollment.Intercept(f(g(h())))`.
func (c *EnrollmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Enrollment = append(c.inters.Enrollment, interceptors...)
}

// Create returns a builder for creating a Enrollment entity.
func (c *EnrollmentClient) Create() *EnrollmentCreate {
	mutation := newEnrollmentMutation(c.config, OpCreate)
	return &EnrollmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Enrollment entities.
func (c *EnrollmentClient) CreateBulk(builders ...*EnrollmentCreate) *EnrollmentCreateBulk {
	return &EnrollmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EnrollmentClient) MapCreateBulk(slice any, setFunc func(*EnrollmentCreate, int)) *EnrollmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EnrollmentCreateBulk{err: fmt.Errorf("calling to EnrollmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EnrollmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EnrollmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Enrollment.
func (c *EnrollmentClient) Update() *EnrollmentUpdate {
	mutation := newEnrollmentMutation(c.config, OpUpdate)
	return &EnrollmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EnrollmentClient) UpdateOne(_m *Enrollment) *EnrollmentUpdateOne {
	mutation := newEnrollmentMutation(c.config, OpUpdateOne, withEnrollment(_m))
	return &EnrollmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EnrollmentClient) UpdateOneID(id int) *EnrollmentUpdateOne {
	mutation := newEnrollmentMutation(c.config, OpUpdateOne, withEnrollmentID(id))
	return &EnrollmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Enrollment.
func (c *EnrollmentClient) Delete() *EnrollmentDelete {
	mutation := newEnrollmentMutation(c.config, OpDelete)
	return &EnrollmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EnrollmentClient) DeleteOne(_m *Enrollment) *EnrollmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EnrollmentClient) DeleteOneID(id int) *EnrollmentDeleteOne {
	builder := c.Delete().Where(enrollment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EnrollmentDeleteOne{builder}
}

// Query returns a query builder for Enrollment.
func (c *EnrollmentClient) Query() *EnrollmentQuery {
	return &EnrollmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEnrollment},
		inters: c.Interceptors(),
	}
}

// Get returns a Enrollment entity by its id.
func (c *EnrollmentClient) Get(ctx context.Context, id int) (*Enrollment, error) {
	return c.Query().Where(enrollment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EnrollmentClient) GetX(ctx context.Context, id int) *Enrollment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStudent queries the student edge of a Enrollment.
func (c *EnrollmentClient) QueryStudent(_m *Enrollment) *StudentQuery {
	query := (&StudentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(enrollment.Table, enrollment.FieldID, id),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, enrollment.StudentTable, enrollment.StudentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCourse queries the course edge of a Enrollment.
func (c *EnrollmentClient) QueryCourse(_m *Enrollment) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(enrollment.Table, enrollment.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, enrollment.CourseTable, enrollment.CourseColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInvoiceLines queries the invoice_lines edge of a Enrollment.
func (c *EnrollmentClient) QueryInvoiceLines(_m *Enrollment) *InvoiceLineQuery {
	query := (&InvoiceLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(enrollment.Table, enrollment.FieldID, id),
			sqlgraph.To(invoiceline.Table, invoiceline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enrollment.InvoiceLinesTable, enrollment.InvoiceLinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPriceOverrides queries the price_overrides edge of a Enrollment.
func (c *EnrollmentClient) QueryPriceOverrides(_m *Enrollment) *PriceOverrideQuery {
	query := (&PriceOverrideClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(enrollment.Table, enrollment.FieldID, id),
			sqlgraph.To(priceoverride.Table, priceoverride.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enrollment.PriceOverridesTable, enrollment.PriceOverridesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EnrollmentClient) Hooks() []Hook {
	return c.hooks.Enrollment
}

// Interceptors returns the client interceptors.
func (c *EnrollmentClient) Interceptors() []Interceptor {
	return c.inters.Enrollment
}

func (c *EnrollmentClient) mutate(ctx context.Context, m *EnrollmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EnrollmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EnrollmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EnrollmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EnrollmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Enrollment mutation op: %q", m.Op())
	}
}

// InvoiceClient is a client for the Invoice schema.
type InvoiceClient struct {
	config
}

// NewInvoiceClient returns a client for the Invoice from the given config.
func NewInvoiceClient(c config) *InvoiceClient {
	return &InvoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invoice.Hooks(f(g(h())))`.
func (c *InvoiceClient) Use(hooks ...Hook) {
	c.hooks.Invoice = append(c.hooks.Invoice, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invoice.Intercept(f(g(h())))`.
func (c *InvoiceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Invoice = append(c.inters.Invoice, interceptors...)
}

// Create returns a builder for creating a Invoice entity.
func (c *InvoiceClient) Create() *InvoiceCreate {
	mutation := newInvoiceMutation(c.config, OpCreate)
	return &InvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Invoice entities.
func (c *InvoiceClient) CreateBulk(builders ...*InvoiceCreate) *InvoiceCreateBulk {
	return &InvoiceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvoiceClient) MapCreateBulk(slice any, setFunc func(*InvoiceCreate, int)) *InvoiceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvoiceCreateBulk{err: fmt.Errorf("calling to InvoiceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvoiceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvoiceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Invoice.
func (c *InvoiceClient) Update() *InvoiceUpdate {
	mutation := newInvoiceMutation(c.config, OpUpdate)
	return &InvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvoiceClient) UpdateOne(_m *Invoice) *InvoiceUpdateOne {
	mutation := newInvoiceMutation(c.config, OpUpdateOne, withInvoice(_m))
	return &InvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvoiceClient) UpdateOneID(id int) *InvoiceUpdateOne {
	mutation := newInvoiceMutation(c.config, OpUpdateOne, withInvoiceID(id))
	return &InvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Invoice.
func (c *InvoiceClient) Delete() *InvoiceDelete {
	mutation := newInvoiceMutation(c.config, OpDelete)
	return &InvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvoiceClient) DeleteOne(_m *Invoice) *InvoiceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvoiceClient) DeleteOneID(id int) *InvoiceDeleteOne {
	builder := c.Delete().Where(invoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvoiceDeleteOne{builder}
}

// Query returns a query builder for Invoice.
func (c *InvoiceClient) Query() *InvoiceQuery {
	return &InvoiceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvoice},
		inters: c.Interceptors(),
	}
}

// Get returns a Invoice entity by its id.
func (c *InvoiceClient) Get(ctx context.Context, id int) (*Invoice, error) {
	return c.Query().Where(invoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvoiceClient) GetX(ctx context.Context, id int) *Invoice {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStudent queries the student edge of a Invoice.
func (c *InvoiceClient) QueryStudent(_m *Invoice) *StudentQuery {
	query := (&StudentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoice.Table, invoice.FieldID, id),
			sqlgraph.To(student.Table, student.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invoice.StudentTable, invoice.StudentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLines queries the lines edge of a Invoice.
func (c *InvoiceClient) QueryLines(_m *Invoice) *InvoiceLineQuery {
	query := (&InvoiceLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoice.Table, invoice.FieldID, id),
			sqlgraph.To(invoiceline.Table, invoiceline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, invoice.LinesTable, invoice.LinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InvoiceClient) Hooks() []Hook {
	return c.hooks.Invoice
}

// Interceptors returns the client interceptors.
func (c *InvoiceClient) Interceptors() []Interceptor {
	return c.inters.Invoice
}

func (c *InvoiceClient) mutate(ctx context.Context, m *InvoiceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Invoice mutation op: %q", m.Op())
	}
}

// InvoiceLineClient is a client for the InvoiceLine schema.
type InvoiceLineClient struct {
	config
}

// NewInvoiceLineClient returns a client for the InvoiceLine from the given config.
func NewInvoiceLineClient(c config) *InvoiceLineClient {
	return &InvoiceLineClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `invoiceline.Hooks(f(g(h())))`.
func (c *InvoiceLineClient) Use(hooks ...Hook) {
	c.hooks.InvoiceLine = append(c.hooks.InvoiceLine, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `invoiceline.Intercept(f(g(h())))`.
func (c *InvoiceLineClient) Intercept(interceptors ...Interceptor) {
	c.inters.InvoiceLine = append(c.inters.InvoiceLine, interceptors...)
}

// Create returns a builder for creating a InvoiceLine entity.
func (c *InvoiceLineClient) Create() *InvoiceLineCreate {
	mutation := newInvoiceLineMutation(c.config, OpCreate)
	return &InvoiceLineCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InvoiceLine entities.
func (c *InvoiceLineClient) CreateBulk(builders ...*InvoiceLineCreate) *InvoiceLineCreateBulk {
	return &InvoiceLineCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InvoiceLineClient) MapCreateBulk(slice any, setFunc func(*InvoiceLineCreate, int)) *InvoiceLineCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InvoiceLineCreateBulk{err: fmt.Errorf("calling to InvoiceLineClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InvoiceLineCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InvoiceLineCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InvoiceLine.
func (c *InvoiceLineClient) Update() *InvoiceLineUpdate {
	mutation := newInvoiceLineMutation(c.config, OpUpdate)
	return &InvoiceLineUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InvoiceLineClient) UpdateOne(_m *InvoiceLine) *InvoiceLineUpdateOne {
	mutation := newInvoiceLineMutation(c.config, OpUpdateOne, withInvoiceLine(_m))
	return &InvoiceLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InvoiceLineClient) UpdateOneID(id int) *InvoiceLineUpdateOne {
	mutation := newInvoiceLineMutation(c.config, OpUpdateOne, withInvoiceLineID(id))
	return &InvoiceLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InvoiceLine.
func (c *InvoiceLineClient) Delete() *InvoiceLineDelete {
	mutation := newInvoiceLineMutation(c.config, OpDelete)
	return &InvoiceLineDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InvoiceLineClient) DeleteOne(_m *InvoiceLine) *InvoiceLineDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InvoiceLineClient) DeleteOneID(id int) *InvoiceLineDeleteOne {
	builder := c.Delete().Where(invoiceline.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InvoiceLineDeleteOne{builder}
}

// Query returns a query builder for InvoiceLine.
func (c *InvoiceLineClient) Query() *InvoiceLineQuery {
	return &InvoiceLineQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInvoiceLine},
		inters: c.Interceptors(),
	}
}

// Get returns a InvoiceLine entity by its id.
func (c *InvoiceLineClient) Get(ctx context.Context, id int) (*InvoiceLine, error) {
	return c.Query().Where(invoiceline.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InvoiceLineClient) GetX(ctx context.Context, id int) *InvoiceLine {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInvoice queries the invoice edge of a InvoiceLine.
func (c *InvoiceLineClient) QueryInvoice(_m *InvoiceLine) *InvoiceQuery {
	query := (&InvoiceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoiceline.Table, invoiceline.FieldID, id),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invoiceline.InvoiceTable, invoiceline.InvoiceColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEnrollment queries the enrollment edge of a InvoiceLine.
func (c *InvoiceLineClient) QueryEnrollment(_m *InvoiceLine) *EnrollmentQuery {
	query := (&EnrollmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(invoiceline.Table, invoiceline.FieldID, id),
			sqlgraph.To(enrollment.Table, enrollment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invoiceline.EnrollmentTable, invoiceline.EnrollmentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InvoiceLineClient) Hooks() []Hook {
	return c.hooks.InvoiceLine
}

// Interceptors returns the client interceptors.
func (c *InvoiceLineClient) Interceptors() []Interceptor {
	return c.inters.InvoiceLine
}

func (c *InvoiceLineClient) mutate(ctx context.Context, m *InvoiceLineMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InvoiceLineCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InvoiceLineUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InvoiceLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InvoiceLineDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InvoiceLine mutation op: %q", m.Op())
	}
}

// PriceOverrideClient is a client for the PriceOverride schema.
type PriceOverrideClient struct {
	config
}

// NewPriceOverrideClient returns a client for the PriceOverride from the given config.
func NewPriceOverrideClient(c config) *PriceOverrideClient {
	return &PriceOverrideClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `priceoverride.Hooks(f(g(h())))`.
func (c *PriceOverrideClient) Use(hooks ...Hook) {
	c.hooks.PriceOverride = append(c.hooks.PriceOverride, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `priceoverride.Intercept(f(g(h())))`.
func (c *PriceOverrideClient) Intercept(interceptors ...Interceptor) {
	c.inters.PriceOverride = append(c.inters.PriceOverride, interceptors...)
}

// Create returns a builder for creating a PriceOverride entity.
func (c *PriceOverrideClient) Create() *PriceOverrideCreate {
	mutation := newPriceOverrideMutation(c.config, OpCreate)
	return &PriceOverrideCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PriceOverride entities.
func (c *PriceOverrideClient) CreateBulk(builders ...*PriceOverrideCreate) *PriceOverrideCreateBulk {
	return &PriceOverrideCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PriceOverrideClient) MapCreateBulk(slice any, setFunc func(*PriceOverrideCreate, int)) *PriceOverrideCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PriceOverrideCreateBulk{err: fmt.Errorf("calling to PriceOverrideClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PriceOverrideCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PriceOverrideCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PriceOverride.
func (c *PriceOverrideClient) Update() *PriceOverrideUpdate {
	mutation := newPriceOverrideMutation(c.config, OpUpdate)
	return &PriceOverrideUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PriceOverrideClient) UpdateOne(_m *PriceOverride) *PriceOverrideUpdateOne {
	mutation := newPriceOverrideMutation(c.config, OpUpdateOne, withPriceOverride(_m))
	return &PriceOverrideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PriceOverrideClient) UpdateOneID(id int) *PriceOverrideUpdateOne {
	mutation := newPriceOverrideMutation(c.config, OpUpdateOne, withPriceOverrideID(id))
	return &PriceOverrideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PriceOverride.
func (c *PriceOverrideClient) Delete() *PriceOverrideDelete {
	mutation := newPriceOverrideMutation(c.config, OpDelete)
	return &PriceOverrideDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PriceOverrideClient) DeleteOne(_m *PriceOverride) *PriceOverrideDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PriceOverrideClient) DeleteOneID(id int) *PriceOverrideDeleteOne {
	builder := c.Delete().Where(priceoverride.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PriceOverrideDeleteOne{builder}
}

// Query returns a query builder for PriceOverride.
func (c *PriceOverrideClient) Query() *PriceOverrideQuery {
	return &PriceOverrideQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePriceOverride},
		inters: c.Interceptors(),
	}
}

// Get returns a PriceOverride entity by its id.
func (c *PriceOverrideClient) Get(ctx context.Context, id int) (*PriceOverride, error) {
	return c.Query().Where(priceoverride.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PriceOverrideClient) GetX(ctx context.Context, id int) *PriceOverride {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEnrollment queries the enrollment edge of a PriceOverride.
func (c *PriceOverrideClient) QueryEnrollment(_m *PriceOverride) *EnrollmentQuery {
	query := (&EnrollmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(priceoverride.Table, priceoverride.FieldID, id),
			sqlgraph.To(enrollment.Table, enrollment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, priceoverride.EnrollmentTable, priceoverride.EnrollmentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PriceOverrideClient) Hooks() []Hook {
	return c.hooks.PriceOverride
}

// Interceptors returns the client interceptors.
func (c *PriceOverrideClient) Interceptors() []Interceptor {
	return c.inters.PriceOverride
}

func (c *PriceOverrideClient) mutate(ctx context.Context, m *PriceOverrideMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PriceOverrideCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PriceOverrideUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PriceOverrideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PriceOverrideDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PriceOverride mutation op: %q", m.Op())
	}
}

// SettingsClient is a client for the Settings schema.
type SettingsClient struct {
	config
}

// NewSettingsClient returns a client for the Settings from the given config.
func NewSettingsClient(c config) *SettingsClient {
	return &SettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `settings.Hooks(f(g(h())))`.
func (c *SettingsClient) Use(hooks ...Hook) {
	c.hooks.Settings = append(c.hooks.Settings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `settings.Intercept(f(g(h())))`.
func (c *SettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Settings = append(c.inters.Settings, interceptors...)
}

// Create returns a builder for creating a Settings entity.
func (c *SettingsClient) Create() *SettingsCreate {
	mutation := newSettingsMutation(c.config, OpCreate)
	return &SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Settings entities.
func (c *SettingsClient) CreateBulk(builders ...*SettingsCreate) *SettingsCreateBulk {
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SettingsClient) MapCreateBulk(slice any, setFunc func(*SettingsCreate, int)) *SettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SettingsCreateBulk{err: fmt.Errorf("calling to SettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Settings.
func (c *SettingsClient) Update() *SettingsUpdate {
	mutation := newSettingsMutation(c.config, OpUpdate)
	return &SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingsClient) UpdateOne(_m *Settings) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettings(_m))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingsClient) UpdateOneID(id int) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettingsID(id))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Settings.
func (c *SettingsClient) Delete() *SettingsDelete {
	mutation := newSettingsMutation(c.config, OpDelete)
	return &SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingsClient) DeleteOne(_m *Settings) *SettingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingsClient) DeleteOneID(id int) *SettingsDeleteOne {
	builder := c.Delete().Where(settings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingsDeleteOne{builder}
}

// Query returns a query builder for Settings.
func (c *SettingsClient) Query() *SettingsQuery {
	return &SettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a Settings entity by its id.
func (c *SettingsClient) Get(ctx context.Context, id int) (*Settings, error) {
	return c.Query().Where(settings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingsClient) GetX(ctx context.Context, id int) *Settings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingsClient) Hooks() []Hook {
	return c.hooks.Settings
}

// Interceptors returns the client interceptors.
func (c *SettingsClient) Interceptors() []Interceptor {
	return c.inters.Settings
}

func (c *SettingsClient) mutate(ctx context.Context, m *SettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Settings mutation op: %q", m.Op())
	}
}

// StudentClient is a client for the Student schema.
type StudentClient struct {
	config
}

// NewStudentClient returns a client for the Student from the given config.
func NewStudentClient(c config) *StudentClient {
	return &StudentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `student.Hooks(f(g(h())))`.
func (c *StudentClient) Use(hooks ...Hook) {
	c.hooks.Student = append(c.hooks.Student, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `student.Intercept(f(g(h())))`.
func (c *StudentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Student = append(c.inters.Student, interceptors...)
}

// Create returns a builder for creating a Student entity.
func (c *StudentClient) Create() *StudentCreate {
	mutation := newStudentMutation(c.config, OpCreate)
	return &StudentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Student entities.
func (c *StudentClient) CreateBulk(builders ...*StudentCreate) *StudentCreateBulk {
	return &StudentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StudentClient) MapCreateBulk(slice any, setFunc func(*StudentCreate, int)) *StudentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StudentCreateBulk{err: fmt.Errorf("calling to StudentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StudentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StudentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Student.
func (c *StudentClient) Update() *StudentUpdate {
	mutation := newStudentMutation(c.config, OpUpdate)
	return &StudentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StudentClient) UpdateOne(_m *Student) *StudentUpdateOne {
	mutation := newStudentMutation(c.config, OpUpdateOne, withStudent(_m))
	return &StudentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StudentClient) UpdateOneID(id int) *StudentUpdateOne {
	mutation := newStudentMutation(c.config, OpUpdateOne, withStudentID(id))
	return &StudentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Student.
func (c *StudentClient) Delete() *StudentDelete {
	mutation := newStudentMutation(c.config, OpDelete)
	return &StudentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StudentClient) DeleteOne(_m *Student) *StudentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StudentClient) DeleteOneID(id int) *StudentDeleteOne {
	builder := c.Delete().Where(student.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StudentDeleteOne{builder}
}

// Query returns a query builder for Student.
func (c *StudentClient) Query() *StudentQuery {
	return &StudentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStudent},
		inters: c.Interceptors(),
	}
}

// Get returns a Student entity by its id.
func (c *StudentClient) Get(ctx context.Context, id int) (*Student, error) {
	return c.Query().Where(student.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StudentClient) GetX(ctx context.Context, id int) *Student {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEnrollments queries the enrollments edge of a Student.
func (c *StudentClient) QueryEnrollments(_m *Student) *EnrollmentQuery {
	query := (&EnrollmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(student.Table, student.FieldID, id),
			sqlgraph.To(enrollment.Table, enrollment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, student.EnrollmentsTable, student.EnrollmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInvoices queries the invoices edge of a Student.
func (c *StudentClient) QueryInvoices(_m *Student) *InvoiceQuery {
	query := (&InvoiceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(student.Table, student.FieldID, id),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, student.InvoicesTable, student.InvoicesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StudentClient) Hooks() []Hook {
	return c.hooks.Student
}

// Interceptors returns the client interceptors.
func (c *StudentClient) Interceptors() []Interceptor {
	return c.inters.Student
}

func (c *StudentClient) mutate(ctx context.Context, m *StudentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StudentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StudentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StudentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StudentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Student mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AttendanceMonth, Course, Enrollment, Invoice, InvoiceLine, PriceOverride,
		Settings, Student []ent.Hook
	}
	inters struct {
		AttendanceMonth, Course, Enrollment, Invoice, InvoiceLine, PriceOverride,
		Settings, Student []ent.Interceptor
	}
)
