// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"langschool/ent/course"
	"langschool/ent/coursemonthstat"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseMonthStatCreate is the builder for creating a CourseMonthStat entity.
type CourseMonthStatCreate struct {
	config
	mutation *CourseMonthStatMutation
	hooks    []Hook
}

// SetCourseID sets the "course_id" field.
func (_c *CourseMonthStatCreate) SetCourseID(v int) *CourseMonthStatCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *CourseMonthStatCreate) SetYear(v int) *CourseMonthStatCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetMonth sets the "month" field.
func (_c *CourseMonthStatCreate) SetMonth(v int) *CourseMonthStatCreate {
	_c.mutation.SetMonth(v)
	return _c
}

// SetSubscriptionLessonsHeld sets the "subscription_lessons_held" field.
func (_c *CourseMonthStatCreate) SetSubscriptionLessonsHeld(v float64) *CourseMonthStatCreate {
	_c.mutation.SetSubscriptionLessonsHeld(v)
	return _c
}

// SetNillableSubscriptionLessonsHeld sets the "subscription_lessons_held" field if the given value is not nil.
func (_c *CourseMonthStatCreate) SetNillableSubscriptionLessonsHeld(v *float64) *CourseMonthStatCreate {
	if v != nil {
		_c.SetSubscriptionLessonsHeld(*v)
	}
	return _c
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *CourseMonthStatCreate) SetCourse(v *Course) *CourseMonthStatCreate {
	return _c.SetCourseID(v.ID)
}

// Mutation returns the CourseMonthStatMutation object of the builder.
func (_c *CourseMonthStatCreate) Mutation() *CourseMonthStatMutation {
	return _c.mutation
}

// Save creates the CourseMonthStat in the database.
func (_c *CourseMonthStatCreate) Save(ctx context.Context) (*CourseMonthStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseMonthStatCreate) SaveX(ctx context.Context) *CourseMonthStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseMonthStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseMonthStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseMonthStatCreate) defaults() {
	if _, ok := _c.mutation.SubscriptionLessonsHeld(); !ok {
		v := coursemonthstat.DefaultSubscriptionLessonsHeld
		_c.mutation.SetSubscriptionLessonsHeld(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseMonthStatCreate) check() error {
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "CourseMonthStat.course_id"`)}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "CourseMonthStat.year"`)}
	}
	if _, ok := _c.mutation.Month(); !ok {
		return &ValidationError{Name: "month", err: errors.New(`ent: missing required field "CourseMonthStat.month"`)}
	}
	if _, ok := _c.mutation.SubscriptionLessonsHeld(); !ok {
		return &ValidationError{Name: "subscription_lessons_held", err: errors.New(`ent: missing required field "CourseMonthStat.subscription_lessons_held"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`ent: missing required edge "CourseMonthStat.course"`)}
	}
	return nil
}

func (_c *CourseMonthStatCreate) sqlSave(ctx context.Context) (*CourseMonthStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseMonthStatCreate) createSpec() (*CourseMonthStat, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseMonthStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coursemonthstat.Table, sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(coursemonthstat.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.Month(); ok {
		_spec.SetField(coursemonthstat.FieldMonth, field.TypeInt, value)
		_node.Month = value
	}
	if value, ok := _c.mutation.SubscriptionLessonsHeld(); ok {
		_spec.SetField(coursemonthstat.FieldSubscriptionLessonsHeld, field.TypeFloat64, value)
		_node.SubscriptionLessonsHeld = value
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemonthstat.CourseTable,
			Columns: []string{coursemonthstat.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseMonthStatCreateBulk is the builder for creating many CourseMonthStat entities in bulk.
type CourseMonthStatCreateBulk struct {
	config
	err      error
	builders []*CourseMonthStatCreate
}

// Save creates the CourseMonthStat entities in the database.
func (_c *CourseMonthStatCreateBulk) Save(ctx context.Context) ([]*CourseMonthStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseMonthStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseMonthStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseMonthStatCreateBulk) SaveX(ctx context.Context) []*CourseMonthStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseMonthStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseMonthStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
