// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"langschool/ent/course"
	"langschool/ent/coursemonthstat"
	"langschool/ent/enrollment"
	"langschool/ent/predicate"
	"langschool/ent/teacher"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CourseUpdate is the builder for updating Course entities.
type CourseUpdate struct {
	config
	hooks    []Hook
	mutation *CourseMutation
}

// Where appends a list predicates to the CourseUpdate builder.
func (_u *CourseUpdate) Where(ps ...predicate.Course) *CourseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CourseUpdate) SetName(v string) *CourseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableName(v *string) *CourseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTeacherName sets the "teacher_name" field.
func (_u *CourseUpdate) SetTeacherName(v string) *CourseUpdate {
	_u.mutation.SetTeacherName(v)
	return _u
}

// SetNillableTeacherName sets the "teacher_name" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableTeacherName(v *string) *CourseUpdate {
	if v != nil {
		_u.SetTeacherName(*v)
	}
	return _u
}

// SetTeacherID sets the "teacher_id" field.
func (_u *CourseUpdate) SetTeacherID(v int) *CourseUpdate {
	_u.mutation.SetTeacherID(v)
	return _u
}

// SetNillableTeacherID sets the "teacher_id" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableTeacherID(v *int) *CourseUpdate {
	if v != nil {
		_u.SetTeacherID(*v)
	}
	return _u
}

// ClearTeacherID clears the value of the "teacher_id" field.
func (_u *CourseUpdate) ClearTeacherID() *CourseUpdate {
	_u.mutation.ClearTeacherID()
	return _u
}

// SetType sets the "type" field.
func (_u *CourseUpdate) SetType(v course.Type) *CourseUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableType(v *course.Type) *CourseUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLegacyLessonPrice sets the "legacy_lesson_price" field.
func (_u *CourseUpdate) SetLegacyLessonPrice(v float64) *CourseUpdate {
	_u.mutation.ResetLegacyLessonPrice()
	_u.mutation.SetLegacyLessonPrice(v)
	return _u
}

// SetNillableLegacyLessonPrice sets the "legacy_lesson_price" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableLegacyLessonPrice(v *float64) *CourseUpdate {
	if v != nil {
		_u.SetLegacyLessonPrice(*v)
	}
	return _u
}

// AddLegacyLessonPrice adds value to the "legacy_lesson_price" field.
func (_u *CourseUpdate) AddLegacyLessonPrice(v float64) *CourseUpdate {
	_u.mutation.AddLegacyLessonPrice(v)
	return _u
}

// SetLegacySubscriptionPrice sets the "legacy_subscription_price" field.
func (_u *CourseUpdate) SetLegacySubscriptionPrice(v float64) *CourseUpdate {
	_u.mutation.ResetLegacySubscriptionPrice()
	_u.mutation.SetLegacySubscriptionPrice(v)
	return _u
}

// SetNillableLegacySubscriptionPrice sets the "legacy_subscription_price" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableLegacySubscriptionPrice(v *float64) *CourseUpdate {
	if v != nil {
		_u.SetLegacySubscriptionPrice(*v)
	}
	return _u
}

// AddLegacySubscriptionPrice adds value to the "legacy_subscription_price" field.
func (_u *CourseUpdate) AddLegacySubscriptionPrice(v float64) *CourseUpdate {
	_u.mutation.AddLegacySubscriptionPrice(v)
	return _u
}

// SetLessonPriceCents sets the "lesson_price_cents" field.
func (_u *CourseUpdate) SetLessonPriceCents(v int64) *CourseUpdate {
	_u.mutation.ResetLessonPriceCents()
	_u.mutation.SetLessonPriceCents(v)
	return _u
}

// SetNillableLessonPriceCents sets the "lesson_price_cents" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableLessonPriceCents(v *int64) *CourseUpdate {
	if v != nil {
		_u.SetLessonPriceCents(*v)
	}
	return _u
}

// AddLessonPriceCents adds value to the "lesson_price_cents" field.
func (_u *CourseUpdate) AddLessonPriceCents(v int64) *CourseUpdate {
	_u.mutation.AddLessonPriceCents(v)
	return _u
}

// SetSubscriptionPriceCents sets the "subscription_price_cents" field.
func (_u *CourseUpdate) SetSubscriptionPriceCents(v int64) *CourseUpdate {
	_u.mutation.ResetSubscriptionPriceCents()
	_u.mutation.SetSubscriptionPriceCents(v)
	return _u
}

// SetNillableSubscriptionPriceCents sets the "subscription_price_cents" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableSubscriptionPriceCents(v *int64) *CourseUpdate {
	if v != nil {
		_u.SetSubscriptionPriceCents(*v)
	}
	return _u
}

// AddSubscriptionPriceCents adds value to the "subscription_price_cents" field.
func (_u *CourseUpdate) AddSubscriptionPriceCents(v int64) *CourseUpdate {
	_u.mutation.AddSubscriptionPriceCents(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CourseUpdate) SetIsActive(v bool) *CourseUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CourseUpdate) SetNillableIsActive(v *bool) *CourseUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetTeacher sets the "teacher" edge to the Teacher entity.
func (_u *CourseUpdate) SetTeacher(v *Teacher) *CourseUpdate {
	return _u.SetTeacherID(v.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the Enrollment entity by IDs.
func (_u *CourseUpdate) AddEnrollmentIDs(ids ...int) *CourseUpdate {
	_u.mutation.AddEnrollmentIDs(ids...)
	return _u
}

// AddEnrollments adds the "enrollments" edges to the Enrollment entity.
func (_u *CourseUpdate) AddEnrollments(v ...*Enrollment) *CourseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollmentIDs(ids...)
}

// AddMonthStatIDs adds the "month_stats" edge to the CourseMonthStat entity by IDs.
func (_u *CourseUpdate) AddMonthStatIDs(ids ...int) *CourseUpdate {
	_u.mutation.AddMonthStatIDs(ids...)
	return _u
}

// AddMonthStats adds the "month_stats" edges to the CourseMonthStat entity.
func (_u *CourseUpdate) AddMonthStats(v ...*CourseMonthStat) *CourseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMonthStatIDs(ids...)
}

// Mutation returns the CourseMutation object of the builder.
func (_u *CourseUpdate) Mutation() *CourseMutation {
	return _u.mutation
}

// ClearTeacher clears the "teacher" edge to the Teacher entity.
func (_u *CourseUpdate) ClearTeacher() *CourseUpdate {
	_u.mutation.ClearTeacher()
	return _u
}

// ClearEnrollments clears all "enrollments" edges to the Enrollment entity.
func (_u *CourseUpdate) ClearEnrollments() *CourseUpdate {
	_u.mutation.ClearEnrollments()
	return _u
}

// RemoveEnrollmentIDs removes the "enrollments" edge to Enrollment entities by IDs.
func (_u *CourseUpdate) RemoveEnrollmentIDs(ids ...int) *CourseUpdate {
	_u.mutation.RemoveEnrollmentIDs(ids...)
	return _u
}

// RemoveEnrollments removes "enrollments" edges to Enrollment entities.
func (_u *CourseUpdate) RemoveEnrollments(v ...*Enrollment) *CourseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollmentIDs(ids...)
}

// ClearMonthStats clears all "month_stats" edges to the CourseMonthStat entity.
func (_u *CourseUpdate) ClearMonthStats() *CourseUpdate {
	_u.mutation.ClearMonthStats()
	return _u
}

// RemoveMonthStatIDs removes the "month_stats" edge to CourseMonthStat entities by IDs.
func (_u *CourseUpdate) RemoveMonthStatIDs(ids ...int) *CourseUpdate {
	_u.mutation.RemoveMonthStatIDs(ids...)
	return _u
}

// RemoveMonthStats removes "month_stats" edges to CourseMonthStat entities.
func (_u *CourseUpdate) RemoveMonthStats(v ...*CourseMonthStat) *CourseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMonthStatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CourseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CourseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CourseUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := course.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Course.type": %w`, err)}
		}
	}
	return nil
}

func (_u *CourseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(course.Table, course.Columns, sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(course.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TeacherName(); ok {
		_spec.SetField(course.FieldTeacherName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(course.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LegacyLessonPrice(); ok {
		_spec.SetField(course.FieldLegacyLessonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLegacyLessonPrice(); ok {
		_spec.AddField(course.FieldLegacyLessonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LegacySubscriptionPrice(); ok {
		_spec.SetField(course.FieldLegacySubscriptionPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLegacySubscriptionPrice(); ok {
		_spec.AddField(course.FieldLegacySubscriptionPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LessonPriceCents(); ok {
		_spec.SetField(course.FieldLessonPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLessonPriceCents(); ok {
		_spec.AddField(course.FieldLessonPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionPriceCents(); ok {
		_spec.SetField(course.FieldSubscriptionPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionPriceCents(); ok {
		_spec.AddField(course.FieldSubscriptionPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(course.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.TeacherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.TeacherTable,
			Columns: []string{course.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.TeacherTable,
			Columns: []string{course.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !_u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MonthStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MonthStatsTable,
			Columns: []string{course.MonthStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMonthStatsIDs(); len(nodes) > 0 && !_u.mutation.MonthStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MonthStatsTable,
			Columns: []string{course.MonthStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonthStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MonthStatsTable,
			Columns: []string{course.MonthStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{course.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CourseUpdateOne is the builder for updating a single Course entity.
type CourseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CourseMutation
}

// SetName sets the "name" field.
func (_u *CourseUpdateOne) SetName(v string) *CourseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableName(v *string) *CourseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTeacherName sets the "teacher_name" field.
func (_u *CourseUpdateOne) SetTeacherName(v string) *CourseUpdateOne {
	_u.mutation.SetTeacherName(v)
	return _u
}

// SetNillableTeacherName sets the "teacher_name" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableTeacherName(v *string) *CourseUpdateOne {
	if v != nil {
		_u.SetTeacherName(*v)
	}
	return _u
}

// SetTeacherID sets the "teacher_id" field.
func (_u *CourseUpdateOne) SetTeacherID(v int) *CourseUpdateOne {
	_u.mutation.SetTeacherID(v)
	return _u
}

// SetNillableTeacherID sets the "teacher_id" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableTeacherID(v *int) *CourseUpdateOne {
	if v != nil {
		_u.SetTeacherID(*v)
	}
	return _u
}

// ClearTeacherID clears the value of the "teacher_id" field.
func (_u *CourseUpdateOne) ClearTeacherID() *CourseUpdateOne {
	_u.mutation.ClearTeacherID()
	return _u
}

// SetType sets the "type" field.
func (_u *CourseUpdateOne) SetType(v course.Type) *CourseUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableType(v *course.Type) *CourseUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLegacyLessonPrice sets the "legacy_lesson_price" field.
func (_u *CourseUpdateOne) SetLegacyLessonPrice(v float64) *CourseUpdateOne {
	_u.mutation.ResetLegacyLessonPrice()
	_u.mutation.SetLegacyLessonPrice(v)
	return _u
}

// SetNillableLegacyLessonPrice sets the "legacy_lesson_price" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableLegacyLessonPrice(v *float64) *CourseUpdateOne {
	if v != nil {
		_u.SetLegacyLessonPrice(*v)
	}
	return _u
}

// AddLegacyLessonPrice adds value to the "legacy_lesson_price" field.
func (_u *CourseUpdateOne) AddLegacyLessonPrice(v float64) *CourseUpdateOne {
	_u.mutation.AddLegacyLessonPrice(v)
	return _u
}

// SetLegacySubscriptionPrice sets the "legacy_subscription_price" field.
func (_u *CourseUpdateOne) SetLegacySubscriptionPrice(v float64) *CourseUpdateOne {
	_u.mutation.ResetLegacySubscriptionPrice()
	_u.mutation.SetLegacySubscriptionPrice(v)
	return _u
}

// SetNillableLegacySubscriptionPrice sets the "legacy_subscription_price" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableLegacySubscriptionPrice(v *float64) *CourseUpdateOne {
	if v != nil {
		_u.SetLegacySubscriptionPrice(*v)
	}
	return _u
}

// AddLegacySubscriptionPrice adds value to the "legacy_subscription_price" field.
func (_u *CourseUpdateOne) AddLegacySubscriptionPrice(v float64) *CourseUpdateOne {
	_u.mutation.AddLegacySubscriptionPrice(v)
	return _u
}

// SetLessonPriceCents sets the "lesson_price_cents" field.
func (_u *CourseUpdateOne) SetLessonPriceCents(v int64) *CourseUpdateOne {
	_u.mutation.ResetLessonPriceCents()
	_u.mutation.SetLessonPriceCents(v)
	return _u
}

// SetNillableLessonPriceCents sets the "lesson_price_cents" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableLessonPriceCents(v *int64) *CourseUpdateOne {
	if v != nil {
		_u.SetLessonPriceCents(*v)
	}
	return _u
}

// AddLessonPriceCents adds value to the "lesson_price_cents" field.
func (_u *CourseUpdateOne) AddLessonPriceCents(v int64) *CourseUpdateOne {
	_u.mutation.AddLessonPriceCents(v)
	return _u
}

// SetSubscriptionPriceCents sets the "subscription_price_cents" field.
func (_u *CourseUpdateOne) SetSubscriptionPriceCents(v int64) *CourseUpdateOne {
	_u.mutation.ResetSubscriptionPriceCents()
	_u.mutation.SetSubscriptionPriceCents(v)
	return _u
}

// SetNillableSubscriptionPriceCents sets the "subscription_price_cents" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableSubscriptionPriceCents(v *int64) *CourseUpdateOne {
	if v != nil {
		_u.SetSubscriptionPriceCents(*v)
	}
	return _u
}

// AddSubscriptionPriceCents adds value to the "subscription_price_cents" field.
func (_u *CourseUpdateOne) AddSubscriptionPriceCents(v int64) *CourseUpdateOne {
	_u.mutation.AddSubscriptionPriceCents(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CourseUpdateOne) SetIsActive(v bool) *CourseUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CourseUpdateOne) SetNillableIsActive(v *bool) *CourseUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetTeacher sets the "teacher" edge to the Teacher entity.
func (_u *CourseUpdateOne) SetTeacher(v *Teacher) *CourseUpdateOne {
	return _u.SetTeacherID(v.ID)
}

// AddEnrollmentIDs adds the "enrollments" edge to the Enrollment entity by IDs.
func (_u *CourseUpdateOne) AddEnrollmentIDs(ids ...int) *CourseUpdateOne {
	_u.mutation.AddEnrollmentIDs(ids...)
	return _u
}

// AddEnrollments adds the "enrollments" edges to the Enrollment entity.
func (_u *CourseUpdateOne) AddEnrollments(v ...*Enrollment) *CourseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnrollmentIDs(ids...)
}

// AddMonthStatIDs adds the "month_stats" edge to the CourseMonthStat entity by IDs.
func (_u *CourseUpdateOne) AddMonthStatIDs(ids ...int) *CourseUpdateOne {
	_u.mutation.AddMonthStatIDs(ids...)
	return _u
}

// AddMonthStats adds the "month_stats" edges to the CourseMonthStat entity.
func (_u *CourseUpdateOne) AddMonthStats(v ...*CourseMonthStat) *CourseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMonthStatIDs(ids...)
}

// Mutation returns the CourseMutation object of the builder.
func (_u *CourseUpdateOne) Mutation() *CourseMutation {
	return _u.mutation
}

// ClearTeacher clears the "teacher" edge to the Teacher entity.
func (_u *CourseUpdateOne) ClearTeacher() *CourseUpdateOne {
	_u.mutation.ClearTeacher()
	return _u
}

// ClearEnrollments clears all "enrollments" edges to the Enrollment entity.
func (_u *CourseUpdateOne) ClearEnrollments() *CourseUpdateOne {
	_u.mutation.ClearEnrollments()
	return _u
}

// RemoveEnrollmentIDs removes the "enrollments" edge to Enrollment entities by IDs.
func (_u *CourseUpdateOne) RemoveEnrollmentIDs(ids ...int) *CourseUpdateOne {
	_u.mutation.RemoveEnrollmentIDs(ids...)
	return _u
}

// RemoveEnrollments removes "enrollments" edges to Enrollment entities.
func (_u *CourseUpdateOne) RemoveEnrollments(v ...*Enrollment) *CourseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnrollmentIDs(ids...)
}

// ClearMonthStats clears all "month_stats" edges to the CourseMonthStat entity.
func (_u *CourseUpdateOne) ClearMonthStats() *CourseUpdateOne {
	_u.mutation.ClearMonthStats()
	return _u
}

// RemoveMonthStatIDs removes the "month_stats" edge to CourseMonthStat entities by IDs.
func (_u *CourseUpdateOne) RemoveMonthStatIDs(ids ...int) *CourseUpdateOne {
	_u.mutation.RemoveMonthStatIDs(ids...)
	return _u
}

// RemoveMonthStats removes "month_stats" edges to CourseMonthStat entities.
func (_u *CourseUpdateOne) RemoveMonthStats(v ...*CourseMonthStat) *CourseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMonthStatIDs(ids...)
}

// Where appends a list predicates to the CourseUpdate builder.
func (_u *CourseUpdateOne) Where(ps ...predicate.Course) *CourseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CourseUpdateOne) Select(field string, fields ...string) *CourseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Course entity.
func (_u *CourseUpdateOne) Save(ctx context.Context) (*Course, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseUpdateOne) SaveX(ctx context.Context) *Course {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CourseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CourseUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := course.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Course.type": %w`, err)}
		}
	}
	return nil
}

func (_u *CourseUpdateOne) sqlSave(ctx context.Context) (_node *Course, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(course.Table, course.Columns, sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Course.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, course.FieldID)
		for _, f := range fields {
			if !course.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != course.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(course.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TeacherName(); ok {
		_spec.SetField(course.FieldTeacherName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(course.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LegacyLessonPrice(); ok {
		_spec.SetField(course.FieldLegacyLessonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLegacyLessonPrice(); ok {
		_spec.AddField(course.FieldLegacyLessonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LegacySubscriptionPrice(); ok {
		_spec.SetField(course.FieldLegacySubscriptionPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLegacySubscriptionPrice(); ok {
		_spec.AddField(course.FieldLegacySubscriptionPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LessonPriceCents(); ok {
		_spec.SetField(course.FieldLessonPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLessonPriceCents(); ok {
		_spec.AddField(course.FieldLessonPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionPriceCents(); ok {
		_spec.SetField(course.FieldSubscriptionPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionPriceCents(); ok {
		_spec.AddField(course.FieldSubscriptionPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(course.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.TeacherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.TeacherTable,
			Columns: []string{course.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.TeacherTable,
			Columns: []string{course.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnrollmentsIDs(); len(nodes) > 0 && !_u.mutation.EnrollmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnrollmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.EnrollmentsTable,
			Columns: []string{course.EnrollmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enrollment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MonthStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MonthStatsTable,
			Columns: []string{course.MonthStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMonthStatsIDs(); len(nodes) > 0 && !_u.mutation.MonthStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MonthStatsTable,
			Columns: []string{course.MonthStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MonthStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MonthStatsTable,
			Columns: []string{course.MonthStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemonthstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Course{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{course.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
