// Code generated by ent, DO NOT EDIT.

package ent

import (
	"langschool/ent/attendancemonth"
	"langschool/ent/auditlog"
	"langschool/ent/course"
	"langschool/ent/coursemonthstat"
	"langschool/ent/enrollment"
	"langschool/ent/invoice"
	"langschool/ent/invoiceline"
	"langschool/ent/payment"
	"langschool/ent/schema"
	"langschool/ent/settings"
	"langschool/ent/student"
	"langschool/ent/teacher"
	"langschool/ent/user"
	"langschool/ent/websession"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attendancemonthFields := schema.AttendanceMonth{}.Fields()
	_ = attendancemonthFields
	// attendancemonthDescHours is the schema descriptor for hours field.
	attendancemonthDescHours := attendancemonthFields[4].Descriptor()
	// attendancemonth.DefaultHours holds the default value on creation for the hours field.
	attendancemonth.DefaultHours = attendancemonthDescHours.Default.(float64)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescActorLabel is the schema descriptor for actor_label field.
	auditlogDescActorLabel := auditlogFields[1].Descriptor()
	// auditlog.DefaultActorLabel holds the default value on creation for the actor_label field.
	auditlog.DefaultActorLabel = auditlogDescActorLabel.Default.(string)
	// auditlogDescBeforeJSON is the schema descriptor for before_json field.
	auditlogDescBeforeJSON := auditlogFields[6].Descriptor()
	// auditlog.DefaultBeforeJSON holds the default value on creation for the before_json field.
	auditlog.DefaultBeforeJSON = auditlogDescBeforeJSON.Default.(string)
	// auditlogDescAfterJSON is the schema descriptor for after_json field.
	auditlogDescAfterJSON := auditlogFields[7].Descriptor()
	// auditlog.DefaultAfterJSON holds the default value on creation for the after_json field.
	auditlog.DefaultAfterJSON = auditlogDescAfterJSON.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[10].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	courseMixin := schema.Course{}.Mixin()
	courseMixinFields0 := courseMixin[0].Fields()
	_ = courseMixinFields0
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescVersion is the schema descriptor for version field.
	courseDescVersion := courseMixinFields0[0].Descriptor()
	// course.DefaultVersion holds the default value on creation for the version field.
	course.DefaultVersion = courseDescVersion.Default.(int)
	// courseDescTeacherName is the schema descriptor for teacher_name field.
	courseDescTeacherName := courseFields[1].Descriptor()
	// course.DefaultTeacherName holds the default value on creation for the teacher_name field.
	course.DefaultTeacherName = courseDescTeacherName.Default.(string)
	// courseDescLegacyLessonPrice is the schema descriptor for legacy_lesson_price field.
	courseDescLegacyLessonPrice := courseFields[4].Descriptor()
	// course.DefaultLegacyLessonPrice holds the default value on creation for the legacy_lesson_price field.
	course.DefaultLegacyLessonPrice = courseDescLegacyLessonPrice.Default.(float64)
	// courseDescLegacySubscriptionPrice is the schema descriptor for legacy_subscription_price field.
	courseDescLegacySubscriptionPrice := courseFields[5].Descriptor()
	// course.DefaultLegacySubscriptionPrice holds the default value on creation for the legacy_subscription_price field.
	course.DefaultLegacySubscriptionPrice = courseDescLegacySubscriptionPrice.Default.(float64)
	// courseDescLessonPriceCents is the schema descriptor for lesson_price_cents field.
	courseDescLessonPriceCents := courseFields[6].Descriptor()
	// course.DefaultLessonPriceCents holds the default value on creation for the lesson_price_cents field.
	course.DefaultLessonPriceCents = courseDescLessonPriceCents.Default.(int64)
	// courseDescSubscriptionPriceCents is the schema descriptor for subscription_price_cents field.
	courseDescSubscriptionPriceCents := courseFields[7].Descriptor()
	// course.DefaultSubscriptionPriceCents holds the default value on creation for the subscription_price_cents field.
	course.DefaultSubscriptionPriceCents = courseDescSubscriptionPriceCents.Default.(int64)
	// courseDescIsActive is the schema descriptor for is_active field.
	courseDescIsActive := courseFields[8].Descriptor()
	// course.DefaultIsActive holds the default value on creation for the is_active field.
	course.DefaultIsActive = courseDescIsActive.Default.(bool)
	coursemonthstatFields := schema.CourseMonthStat{}.Fields()
	_ = coursemonthstatFields
	// coursemonthstatDescSubscriptionLessonsHeld is the schema descriptor for subscription_lessons_held field.
	coursemonthstatDescSubscriptionLessonsHeld := coursemonthstatFields[3].Descriptor()
	// coursemonthstat.DefaultSubscriptionLessonsHeld holds the default value on creation for the subscription_lessons_held field.
	coursemonthstat.DefaultSubscriptionLessonsHeld = coursemonthstatDescSubscriptionLessonsHeld.Default.(float64)
	enrollmentMixin := schema.Enrollment{}.Mixin()
	enrollmentMixinFields0 := enrollmentMixin[0].Fields()
	_ = enrollmentMixinFields0
	enrollmentFields := schema.Enrollment{}.Fields()
	_ = enrollmentFields
	// enrollmentDescVersion is the schema descriptor for version field.
	enrollmentDescVersion := enrollmentMixinFields0[0].Descriptor()
	// enrollment.DefaultVersion holds the default value on creation for the version field.
	enrollment.DefaultVersion = enrollmentDescVersion.Default.(int)
	// enrollmentDescChargeMaterials is the schema descriptor for charge_materials field.
	enrollmentDescChargeMaterials := enrollmentFields[3].Descriptor()
	// enrollment.DefaultChargeMaterials holds the default value on creation for the charge_materials field.
	enrollment.DefaultChargeMaterials = enrollmentDescChargeMaterials.Default.(bool)
	// enrollmentDescDiscountPct is the schema descriptor for discount_pct field.
	enrollmentDescDiscountPct := enrollmentFields[4].Descriptor()
	// enrollment.DefaultDiscountPct holds the default value on creation for the discount_pct field.
	enrollment.DefaultDiscountPct = enrollmentDescDiscountPct.Default.(float64)
	// enrollmentDescLessonPriceOverrideCents is the schema descriptor for lesson_price_override_cents field.
	enrollmentDescLessonPriceOverrideCents := enrollmentFields[5].Descriptor()
	// enrollment.DefaultLessonPriceOverrideCents holds the default value on creation for the lesson_price_override_cents field.
	enrollment.DefaultLessonPriceOverrideCents = enrollmentDescLessonPriceOverrideCents.Default.(int64)
	// enrollmentDescSubscriptionLessonPriceCents is the schema descriptor for subscription_lesson_price_cents field.
	enrollmentDescSubscriptionLessonPriceCents := enrollmentFields[6].Descriptor()
	// enrollment.DefaultSubscriptionLessonPriceCents holds the default value on creation for the subscription_lesson_price_cents field.
	enrollment.DefaultSubscriptionLessonPriceCents = enrollmentDescSubscriptionLessonPriceCents.Default.(int64)
	// enrollmentDescNote is the schema descriptor for note field.
	enrollmentDescNote := enrollmentFields[7].Descriptor()
	// enrollment.DefaultNote holds the default value on creation for the note field.
	enrollment.DefaultNote = enrollmentDescNote.Default.(string)
	// enrollmentDescCreatedAt is the schema descriptor for created_at field.
	enrollmentDescCreatedAt := enrollmentFields[8].Descriptor()
	// enrollment.DefaultCreatedAt holds the default value on creation for the created_at field.
	enrollment.DefaultCreatedAt = enrollmentDescCreatedAt.Default.(func() time.Time)
	// enrollmentDescUpdatedAt is the schema descriptor for updated_at field.
	enrollmentDescUpdatedAt := enrollmentFields[9].Descriptor()
	// enrollment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	enrollment.DefaultUpdatedAt = enrollmentDescUpdatedAt.Default.(func() time.Time)
	// enrollment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	enrollment.UpdateDefaultUpdatedAt = enrollmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	invoiceMixin := schema.Invoice{}.Mixin()
	invoiceMixinFields0 := invoiceMixin[0].Fields()
	_ = invoiceMixinFields0
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescVersion is the schema descriptor for version field.
	invoiceDescVersion := invoiceMixinFields0[0].Descriptor()
	// invoice.DefaultVersion holds the default value on creation for the version field.
	invoice.DefaultVersion = invoiceDescVersion.Default.(int)
	// invoiceDescLegacyTotalAmount is the schema descriptor for legacy_total_amount field.
	invoiceDescLegacyTotalAmount := invoiceFields[3].Descriptor()
	// invoice.DefaultLegacyTotalAmount holds the default value on creation for the legacy_total_amount field.
	invoice.DefaultLegacyTotalAmount = invoiceDescLegacyTotalAmount.Default.(float64)
	// invoiceDescTotalAmountCents is the schema descriptor for total_amount_cents field.
	invoiceDescTotalAmountCents := invoiceFields[4].Descriptor()
	// invoice.DefaultTotalAmountCents holds the default value on creation for the total_amount_cents field.
	invoice.DefaultTotalAmountCents = invoiceDescTotalAmountCents.Default.(int64)
	// invoiceDescCreatedAt is the schema descriptor for created_at field.
	invoiceDescCreatedAt := invoiceFields[16].Descriptor()
	// invoice.DefaultCreatedAt holds the default value on creation for the created_at field.
	invoice.DefaultCreatedAt = invoiceDescCreatedAt.Default.(func() time.Time)
	// invoiceDescUpdatedAt is the schema descriptor for updated_at field.
	invoiceDescUpdatedAt := invoiceFields[17].Descriptor()
	// invoice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invoice.DefaultUpdatedAt = invoiceDescUpdatedAt.Default.(func() time.Time)
	// invoice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invoice.UpdateDefaultUpdatedAt = invoiceDescUpdatedAt.UpdateDefault.(func() time.Time)
	invoicelineFields := schema.InvoiceLine{}.Fields()
	_ = invoicelineFields
	// invoicelineDescLegacyUnitPrice is the schema descriptor for legacy_unit_price field.
	invoicelineDescLegacyUnitPrice := invoicelineFields[4].Descriptor()
	// invoiceline.DefaultLegacyUnitPrice holds the default value on creation for the legacy_unit_price field.
	invoiceline.DefaultLegacyUnitPrice = invoicelineDescLegacyUnitPrice.Default.(float64)
	// invoicelineDescLegacyAmount is the schema descriptor for legacy_amount field.
	invoicelineDescLegacyAmount := invoicelineFields[5].Descriptor()
	// invoiceline.DefaultLegacyAmount holds the default value on creation for the legacy_amount field.
	invoiceline.DefaultLegacyAmount = invoicelineDescLegacyAmount.Default.(float64)
	// invoicelineDescUnitPriceCents is the schema descriptor for unit_price_cents field.
	invoicelineDescUnitPriceCents := invoicelineFields[6].Descriptor()
	// invoiceline.DefaultUnitPriceCents holds the default value on creation for the unit_price_cents field.
	invoiceline.DefaultUnitPriceCents = invoicelineDescUnitPriceCents.Default.(int64)
	// invoicelineDescAmountCents is the schema descriptor for amount_cents field.
	invoicelineDescAmountCents := invoicelineFields[7].Descriptor()
	// invoiceline.DefaultAmountCents holds the default value on creation for the amount_cents field.
	invoiceline.DefaultAmountCents = invoicelineDescAmountCents.Default.(int64)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescPaidAt is the schema descriptor for paid_at field.
	paymentDescPaidAt := paymentFields[2].Descriptor()
	// payment.DefaultPaidAt holds the default value on creation for the paid_at field.
	payment.DefaultPaidAt = paymentDescPaidAt.Default.(func() time.Time)
	// paymentDescLegacyAmount is the schema descriptor for legacy_amount field.
	paymentDescLegacyAmount := paymentFields[3].Descriptor()
	// payment.DefaultLegacyAmount holds the default value on creation for the legacy_amount field.
	payment.DefaultLegacyAmount = paymentDescLegacyAmount.Default.(float64)
	// paymentDescAmountCents is the schema descriptor for amount_cents field.
	paymentDescAmountCents := paymentFields[4].Descriptor()
	// payment.DefaultAmountCents holds the default value on creation for the amount_cents field.
	payment.DefaultAmountCents = paymentDescAmountCents.Default.(int64)
	// paymentDescNote is the schema descriptor for note field.
	paymentDescNote := paymentFields[6].Descriptor()
	// payment.DefaultNote holds the default value on creation for the note field.
	payment.DefaultNote = paymentDescNote.Default.(string)
	// paymentDescCreatedAt is the schema descriptor for created_at field.
	paymentDescCreatedAt := paymentFields[7].Descriptor()
	// payment.DefaultCreatedAt holds the default value on creation for the created_at field.
	payment.DefaultCreatedAt = paymentDescCreatedAt.Default.(func() time.Time)
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescOrgName is the schema descriptor for org_name field.
	settingsDescOrgName := settingsFields[1].Descriptor()
	// settings.DefaultOrgName holds the default value on creation for the org_name field.
	settings.DefaultOrgName = settingsDescOrgName.Default.(string)
	// settingsDescAddress is the schema descriptor for address field.
	settingsDescAddress := settingsFields[2].Descriptor()
	// settings.DefaultAddress holds the default value on creation for the address field.
	settings.DefaultAddress = settingsDescAddress.Default.(string)
	// settingsDescInvoicePrefix is the schema descriptor for invoice_prefix field.
	settingsDescInvoicePrefix := settingsFields[3].Descriptor()
	// settings.DefaultInvoicePrefix holds the default value on creation for the invoice_prefix field.
	settings.DefaultInvoicePrefix = settingsDescInvoicePrefix.Default.(string)
	// settingsDescNextSeq is the schema descriptor for next_seq field.
	settingsDescNextSeq := settingsFields[4].Descriptor()
	// settings.DefaultNextSeq holds the default value on creation for the next_seq field.
	settings.DefaultNextSeq = settingsDescNextSeq.Default.(int)
	// settingsDescInvoiceDayOfMonth is the schema descriptor for invoice_day_of_month field.
	settingsDescInvoiceDayOfMonth := settingsFields[5].Descriptor()
	// settings.DefaultInvoiceDayOfMonth holds the default value on creation for the invoice_day_of_month field.
	settings.DefaultInvoiceDayOfMonth = settingsDescInvoiceDayOfMonth.Default.(int)
	// settingsDescCurrency is the schema descriptor for currency field.
	settingsDescCurrency := settingsFields[6].Descriptor()
	// settings.DefaultCurrency holds the default value on creation for the currency field.
	settings.DefaultCurrency = settingsDescCurrency.Default.(string)
	// settingsDescLocale is the schema descriptor for locale field.
	settingsDescLocale := settingsFields[7].Descriptor()
	// settings.DefaultLocale holds the default value on creation for the locale field.
	settings.DefaultLocale = settingsDescLocale.Default.(string)
	// settingsDescInvoiceEmailSubjectTemplate is the schema descriptor for invoice_email_subject_template field.
	settingsDescInvoiceEmailSubjectTemplate := settingsFields[8].Descriptor()
	// settings.DefaultInvoiceEmailSubjectTemplate holds the default value on creation for the invoice_email_subject_template field.
	settings.DefaultInvoiceEmailSubjectTemplate = settingsDescInvoiceEmailSubjectTemplate.Default.(string)
	// settingsDescInvoiceEmailBodyTemplate is the schema descriptor for invoice_email_body_template field.
	settingsDescInvoiceEmailBodyTemplate := settingsFields[9].Descriptor()
	// settings.DefaultInvoiceEmailBodyTemplate holds the default value on creation for the invoice_email_body_template field.
	settings.DefaultInvoiceEmailBodyTemplate = settingsDescInvoiceEmailBodyTemplate.Default.(string)
	// settingsDescInvoiceReplyTo is the schema descriptor for invoice_reply_to field.
	settingsDescInvoiceReplyTo := settingsFields[10].Descriptor()
	// settings.DefaultInvoiceReplyTo holds the default value on creation for the invoice_reply_to field.
	settings.DefaultInvoiceReplyTo = settingsDescInvoiceReplyTo.Default.(string)
	// settingsDescMoneyCentsMigrated is the schema descriptor for money_cents_migrated field.
	settingsDescMoneyCentsMigrated := settingsFields[11].Descriptor()
	// settings.DefaultMoneyCentsMigrated holds the default value on creation for the money_cents_migrated field.
	settings.DefaultMoneyCentsMigrated = settingsDescMoneyCentsMigrated.Default.(bool)
	studentMixin := schema.Student{}.Mixin()
	studentMixinFields0 := studentMixin[0].Fields()
	_ = studentMixinFields0
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescVersion is the schema descriptor for version field.
	studentDescVersion := studentMixinFields0[0].Descriptor()
	// student.DefaultVersion holds the default value on creation for the version field.
	student.DefaultVersion = studentDescVersion.Default.(int)
	// studentDescCreatedAt is the schema descriptor for created_at field.
	studentDescCreatedAt := studentFields[1].Descriptor()
	// student.DefaultCreatedAt holds the default value on creation for the created_at field.
	student.DefaultCreatedAt = studentDescCreatedAt.Default.(func() time.Time)
	// studentDescPersonalCode is the schema descriptor for personal_code field.
	studentDescPersonalCode := studentFields[2].Descriptor()
	// student.DefaultPersonalCode holds the default value on creation for the personal_code field.
	student.DefaultPersonalCode = studentDescPersonalCode.Default.(string)
	// studentDescPhone is the schema descriptor for phone field.
	studentDescPhone := studentFields[3].Descriptor()
	// student.DefaultPhone holds the default value on creation for the phone field.
	student.DefaultPhone = studentDescPhone.Default.(string)
	// studentDescEmail is the schema descriptor for email field.
	studentDescEmail := studentFields[4].Descriptor()
	// student.DefaultEmail holds the default value on creation for the email field.
	student.DefaultEmail = studentDescEmail.Default.(string)
	// studentDescNote is the schema descriptor for note field.
	studentDescNote := studentFields[5].Descriptor()
	// student.DefaultNote holds the default value on creation for the note field.
	student.DefaultNote = studentDescNote.Default.(string)
	// studentDescIsMinor is the schema descriptor for is_minor field.
	studentDescIsMinor := studentFields[6].Descriptor()
	// student.DefaultIsMinor holds the default value on creation for the is_minor field.
	student.DefaultIsMinor = studentDescIsMinor.Default.(bool)
	// studentDescPayerName is the schema descriptor for payer_name field.
	studentDescPayerName := studentFields[7].Descriptor()
	// student.DefaultPayerName holds the default value on creation for the payer_name field.
	student.DefaultPayerName = studentDescPayerName.Default.(string)
	// studentDescPayerRole is the schema descriptor for payer_role field.
	studentDescPayerRole := studentFields[8].Descriptor()
	// student.DefaultPayerRole holds the default value on creation for the payer_role field.
	student.DefaultPayerRole = studentDescPayerRole.Default.(string)
	// studentDescIsActive is the schema descriptor for is_active field.
	studentDescIsActive := studentFields[9].Descriptor()
	// student.DefaultIsActive holds the default value on creation for the is_active field.
	student.DefaultIsActive = studentDescIsActive.Default.(bool)
	teacherFields := schema.Teacher{}.Fields()
	_ = teacherFields
	// teacherDescIsActive is the schema descriptor for is_active field.
	teacherDescIsActive := teacherFields[1].Descriptor()
	// teacher.DefaultIsActive holds the default value on creation for the is_active field.
	teacher.DefaultIsActive = teacherDescIsActive.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescUILocale is the schema descriptor for ui_locale field.
	userDescUILocale := userFields[4].Descriptor()
	// user.DefaultUILocale holds the default value on creation for the ui_locale field.
	user.DefaultUILocale = userDescUILocale.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	websessionFields := schema.WebSession{}.Fields()
	_ = websessionFields
	// websessionDescCreatedAt is the schema descriptor for created_at field.
	websessionDescCreatedAt := websessionFields[2].Descriptor()
	// websession.DefaultCreatedAt holds the default value on creation for the created_at field.
	websession.DefaultCreatedAt = websessionDescCreatedAt.Default.(func() time.Time)
	// websessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	websessionDescLastSeenAt := websessionFields[3].Descriptor()
	// websession.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	websession.DefaultLastSeenAt = websessionDescLastSeenAt.Default.(func() time.Time)
	// websession.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	websession.UpdateDefaultLastSeenAt = websessionDescLastSeenAt.UpdateDefault.(func() time.Time)
}
