// Code generated by ent, DO NOT EDIT.

package ent

import (
	"langschool/ent/attendancemonth"
	"langschool/ent/course"
	"langschool/ent/enrollment"
	"langschool/ent/invoice"
	"langschool/ent/schema"
	"langschool/ent/settings"
	"langschool/ent/student"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attendancemonthFields := schema.AttendanceMonth{}.Fields()
	_ = attendancemonthFields
	// attendancemonthDescLessonsCount is the schema descriptor for lessons_count field.
	attendancemonthDescLessonsCount := attendancemonthFields[4].Descriptor()
	// attendancemonth.DefaultLessonsCount holds the default value on creation for the lessons_count field.
	attendancemonth.DefaultLessonsCount = attendancemonthDescLessonsCount.Default.(int)
	// attendancemonthDescLocked is the schema descriptor for locked field.
	attendancemonthDescLocked := attendancemonthFields[5].Descriptor()
	// attendancemonth.DefaultLocked holds the default value on creation for the locked field.
	attendancemonth.DefaultLocked = attendancemonthDescLocked.Default.(bool)
	courseFields := schema.Course{}.Fields()
	_ = courseFields
	// courseDescLessonPrice is the schema descriptor for lesson_price field.
	courseDescLessonPrice := courseFields[2].Descriptor()
	// course.DefaultLessonPrice holds the default value on creation for the lesson_price field.
	course.DefaultLessonPrice = courseDescLessonPrice.Default.(float64)
	// courseDescSubscriptionPrice is the schema descriptor for subscription_price field.
	courseDescSubscriptionPrice := courseFields[3].Descriptor()
	// course.DefaultSubscriptionPrice holds the default value on creation for the subscription_price field.
	course.DefaultSubscriptionPrice = courseDescSubscriptionPrice.Default.(float64)
	// courseDescScheduleJSON is the schema descriptor for schedule_json field.
	courseDescScheduleJSON := courseFields[4].Descriptor()
	// course.DefaultScheduleJSON holds the default value on creation for the schedule_json field.
	course.DefaultScheduleJSON = courseDescScheduleJSON.Default.(string)
	// courseDescIsActive is the schema descriptor for is_active field.
	courseDescIsActive := courseFields[5].Descriptor()
	// course.DefaultIsActive holds the default value on creation for the is_active field.
	course.DefaultIsActive = courseDescIsActive.Default.(bool)
	enrollmentFields := schema.Enrollment{}.Fields()
	_ = enrollmentFields
	// enrollmentDescDiscountPct is the schema descriptor for discount_pct field.
	enrollmentDescDiscountPct := enrollmentFields[5].Descriptor()
	// enrollment.DefaultDiscountPct holds the default value on creation for the discount_pct field.
	enrollment.DefaultDiscountPct = enrollmentDescDiscountPct.Default.(float64)
	// enrollmentDescNote is the schema descriptor for note field.
	enrollmentDescNote := enrollmentFields[6].Descriptor()
	// enrollment.DefaultNote holds the default value on creation for the note field.
	enrollment.DefaultNote = enrollmentDescNote.Default.(string)
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescTotalAmount is the schema descriptor for total_amount field.
	invoiceDescTotalAmount := invoiceFields[3].Descriptor()
	// invoice.DefaultTotalAmount holds the default value on creation for the total_amount field.
	invoice.DefaultTotalAmount = invoiceDescTotalAmount.Default.(float64)
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescOrgName is the schema descriptor for org_name field.
	settingsDescOrgName := settingsFields[1].Descriptor()
	// settings.DefaultOrgName holds the default value on creation for the org_name field.
	settings.DefaultOrgName = settingsDescOrgName.Default.(string)
	// settingsDescAddress is the schema descriptor for address field.
	settingsDescAddress := settingsFields[2].Descriptor()
	// settings.DefaultAddress holds the default value on creation for the address field.
	settings.DefaultAddress = settingsDescAddress.Default.(string)
	// settingsDescInvoicePrefix is the schema descriptor for invoice_prefix field.
	settingsDescInvoicePrefix := settingsFields[3].Descriptor()
	// settings.DefaultInvoicePrefix holds the default value on creation for the invoice_prefix field.
	settings.DefaultInvoicePrefix = settingsDescInvoicePrefix.Default.(string)
	// settingsDescNextSeq is the schema descriptor for next_seq field.
	settingsDescNextSeq := settingsFields[4].Descriptor()
	// settings.DefaultNextSeq holds the default value on creation for the next_seq field.
	settings.DefaultNextSeq = settingsDescNextSeq.Default.(int)
	// settingsDescInvoiceDayOfMonth is the schema descriptor for invoice_day_of_month field.
	settingsDescInvoiceDayOfMonth := settingsFields[5].Descriptor()
	// settings.DefaultInvoiceDayOfMonth holds the default value on creation for the invoice_day_of_month field.
	settings.DefaultInvoiceDayOfMonth = settingsDescInvoiceDayOfMonth.Default.(int)
	// settingsDescAutoIssue is the schema descriptor for auto_issue field.
	settingsDescAutoIssue := settingsFields[6].Descriptor()
	// settings.DefaultAutoIssue holds the default value on creation for the auto_issue field.
	settings.DefaultAutoIssue = settingsDescAutoIssue.Default.(bool)
	// settingsDescCurrency is the schema descriptor for currency field.
	settingsDescCurrency := settingsFields[7].Descriptor()
	// settings.DefaultCurrency holds the default value on creation for the currency field.
	settings.DefaultCurrency = settingsDescCurrency.Default.(string)
	// settingsDescLocale is the schema descriptor for locale field.
	settingsDescLocale := settingsFields[8].Descriptor()
	// settings.DefaultLocale holds the default value on creation for the locale field.
	settings.DefaultLocale = settingsDescLocale.Default.(string)
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescPhone is the schema descriptor for phone field.
	studentDescPhone := studentFields[1].Descriptor()
	// student.DefaultPhone holds the default value on creation for the phone field.
	student.DefaultPhone = studentDescPhone.Default.(string)
	// studentDescEmail is the schema descriptor for email field.
	studentDescEmail := studentFields[2].Descriptor()
	// student.DefaultEmail holds the default value on creation for the email field.
	student.DefaultEmail = studentDescEmail.Default.(string)
	// studentDescNote is the schema descriptor for note field.
	studentDescNote := studentFields[3].Descriptor()
	// student.DefaultNote holds the default value on creation for the note field.
	student.DefaultNote = studentDescNote.Default.(string)
	// studentDescIsActive is the schema descriptor for is_active field.
	studentDescIsActive := studentFields[4].Descriptor()
	// student.DefaultIsActive holds the default value on creation for the is_active field.
	student.DefaultIsActive = studentDescIsActive.Default.(bool)
}
