// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"langschool/ent/contact"
	"langschool/ent/student"
	"langschool/ent/studentcontact"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentContactCreate is the builder for creating a StudentContact entity.
type StudentContactCreate struct {
	config
	mutation *StudentContactMutation
	hooks    []Hook
}

// SetStudentID sets the "student_id" field.
func (_c *StudentContactCreate) SetStudentID(v int) *StudentContactCreate {
	_c.mutation.SetStudentID(v)
	return _c
}

// SetContactID sets the "contact_id" field.
func (_c *StudentContactCreate) SetContactID(v int) *StudentContactCreate {
	_c.mutation.SetContactID(v)
	return _c
}

// SetRelation sets the "relation" field.
func (_c *StudentContactCreate) SetRelation(v string) *StudentContactCreate {
	_c.mutation.SetRelation(v)
	return _c
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableRelation(v *string) *StudentContactCreate {
	if v != nil {
		_c.SetRelation(*v)
	}
	return _c
}

// SetIsPrimary sets the "is_primary" field.
func (_c *StudentContactCreate) SetIsPrimary(v bool) *StudentContactCreate {
	_c.mutation.SetIsPrimary(v)
	return _c
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableIsPrimary(v *bool) *StudentContactCreate {
	if v != nil {
		_c.SetIsPrimary(*v)
	}
	return _c
}

// SetIsPayer sets the "is_payer" field.
func (_c *StudentContactCreate) SetIsPayer(v bool) *StudentContactCreate {
	_c.mutation.SetIsPayer(v)
	return _c
}

// SetNillableIsPayer sets the "is_payer" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableIsPayer(v *bool) *StudentContactCreate {
	if v != nil {
		_c.SetIsPayer(*v)
	}
	return _c
}

// SetReceivesMessages sets the "receives_messages" field.
func (_c *StudentContactCreate) SetReceivesMessages(v bool) *StudentContactCreate {
	_c.mutation.SetReceivesMessages(v)
	return _c
}

// SetNillableReceivesMessages sets the "receives_messages" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableReceivesMessages(v *bool) *StudentContactCreate {
	if v != nil {
		_c.SetReceivesMessages(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *StudentContactCreate) SetNote(v string) *StudentContactCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableNote(v *string) *StudentContactCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StudentContactCreate) SetCreatedAt(v time.Time) *StudentContactCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableCreatedAt(v *time.Time) *StudentContactCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StudentContactCreate) SetUpdatedAt(v time.Time) *StudentContactCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StudentContactCreate) SetNillableUpdatedAt(v *time.Time) *StudentContactCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStudent sets the "student" edge to the Student entity.
func (_c *StudentContactCreate) SetStudent(v *Student) *StudentContactCreate {
	return _c.SetStudentID(v.ID)
}

// SetContact sets the "contact" edge to the Contact entity.
func (_c *StudentContactCreate) SetContact(v *Contact) *StudentContactCreate {
	return _c.SetContactID(v.ID)
}

// Mutation returns the StudentContactMutation object of the builder.
func (_c *StudentContactCreate) Mutation() *StudentContactMutation {
	return _c.mutation
}

// Save creates the StudentContact in the database.
func (_c *StudentContactCreate) Save(ctx context.Context) (*StudentContact, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StudentContactCreate) SaveX(ctx context.Context) *StudentContact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudentContactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudentContactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StudentContactCreate) defaults() {
	if _, ok := _c.mutation.Relation(); !ok {
		v := studentcontact.DefaultRelation
		_c.mutation.SetRelation(v)
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		v := studentcontact.DefaultIsPrimary
		_c.mutation.SetIsPrimary(v)
	}
	if _, ok := _c.mutation.IsPayer(); !ok {
		v := studentcontact.DefaultIsPayer
		_c.mutation.SetIsPayer(v)
	}
	if _, ok := _c.mutation.ReceivesMessages(); !ok {
		v := studentcontact.DefaultReceivesMessages
		_c.mutation.SetReceivesMessages(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := studentcontact.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := studentcontact.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := studentcontact.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StudentContactCreate) check() error {
	if _, ok := _c.mutation.StudentID(); !ok {
		return &ValidationError{Name: "student_id", err: errors.New(`ent: missing required field "StudentContact.student_id"`)}
	}
	if _, ok := _c.mutation.ContactID(); !ok {
		return &ValidationError{Name: "contact_id", err: errors.New(`ent: missing required field "StudentContact.contact_id"`)}
	}
	if _, ok := _c.mutation.Relation(); !ok {
		return &ValidationError{Name: "relation", err: errors.New(`ent: missing required field "StudentContact.relation"`)}
	}
	if _, ok := _c.mutation.IsPrimary(); !ok {
		return &ValidationError{Name: "is_primary", err: errors.New(`ent: missing required field "StudentContact.is_primary"`)}
	}
	if _, ok := _c.mutation.IsPayer(); !ok {
		return &ValidationError{Name: "is_payer", err: errors.New(`ent: missing required field "StudentContact.is_payer"`)}
	}
	if _, ok := _c.mutation.ReceivesMessages(); !ok {
		return &ValidationError{Name: "receives_messages", err: errors.New(`ent: missing required field "StudentContact.receives_messages"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "StudentContact.note"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StudentContact.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StudentContact.updated_at"`)}
	}
	if len(_c.mutation.StudentIDs()) == 0 {
		return &ValidationError{Name: "student", err: errors.New(`ent: missing required edge "StudentContact.student"`)}
	}
	if len(_c.mutation.ContactIDs()) == 0 {
		return &ValidationError{Name: "contact", err: errors.New(`ent: missing required edge "StudentContact.contact"`)}
	}
	return nil
}

func (_c *StudentContactCreate) sqlSave(ctx context.Context) (*StudentContact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StudentContactCreate) createSpec() (*StudentContact, *sqlgraph.CreateSpec) {
	var (
		_node = &StudentContact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(studentcontact.Table, sqlgraph.NewFieldSpec(studentcontact.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Relation(); ok {
		_spec.SetField(studentcontact.FieldRelation, field.TypeString, value)
		_node.Relation = value
	}
	if value, ok := _c.mutation.IsPrimary(); ok {
		_spec.SetField(studentcontact.FieldIsPrimary, field.TypeBool, value)
		_node.IsPrimary = value
	}
	if value, ok := _c.mutation.IsPayer(); ok {
		_spec.SetField(studentcontact.FieldIsPayer, field.TypeBool, value)
		_node.IsPayer = value
	}
	if value, ok := _c.mutation.ReceivesMessages(); ok {
		_spec.SetField(studentcontact.FieldReceivesMessages, field.TypeBool, value)
		_node.ReceivesMessages = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(studentcontact.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(studentcontact.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(studentcontact.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   studentcontact.StudentTable,
			Columns: []string{studentcontact.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StudentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   studentcontact.ContactTable,
			Columns: []string{studentcontact.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContactID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StudentContactCreateBulk is the builder for creating many StudentContact entities in bulk.
type StudentContactCreateBulk struct {
	config
	err      error
	builders []*StudentContactCreate
}

// Save creates the StudentContact entities in the database.
func (_c *StudentContactCreateBulk) Save(ctx context.Context) ([]*StudentContact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StudentContact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentContactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StudentContactCreateBulk) SaveX(ctx context.Context) []*StudentContact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudentContactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudentContactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
