// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"langschool/ent/predicate"
	"langschool/ent/user"
	"langschool/ent/websession"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebSessionUpdate is the builder for updating WebSession entities.
type WebSessionUpdate struct {
	config
	hooks    []Hook
	mutation *WebSessionMutation
}

// Where appends a list predicates to the WebSessionUpdate builder.
func (_u *WebSessionUpdate) Where(ps ...predicate.WebSession) *WebSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *WebSessionUpdate) SetTokenHash(v string) *WebSessionUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *WebSessionUpdate) SetNillableTokenHash(v *string) *WebSessionUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *WebSessionUpdate) SetExpiresAt(v time.Time) *WebSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *WebSessionUpdate) SetNillableExpiresAt(v *time.Time) *WebSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WebSessionUpdate) SetCreatedAt(v time.Time) *WebSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WebSessionUpdate) SetNillableCreatedAt(v *time.Time) *WebSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *WebSessionUpdate) SetLastSeenAt(v time.Time) *WebSessionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *WebSessionUpdate) SetUserID(id int) *WebSessionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WebSessionUpdate) SetUser(v *User) *WebSessionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WebSessionMutation object of the builder.
func (_u *WebSessionUpdate) Mutation() *WebSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WebSessionUpdate) ClearUser() *WebSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebSessionUpdate) defaults() {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := websession.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebSessionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebSession.user"`)
	}
	return nil
}

func (_u *WebSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(websession.Table, websession.Columns, sqlgraph.NewFieldSpec(websession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(websession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(websession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(websession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(websession.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   websession.UserTable,
			Columns: []string{websession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   websession.UserTable,
			Columns: []string{websession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{websession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebSessionUpdateOne is the builder for updating a single WebSession entity.
type WebSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebSessionMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *WebSessionUpdateOne) SetTokenHash(v string) *WebSessionUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *WebSessionUpdateOne) SetNillableTokenHash(v *string) *WebSessionUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *WebSessionUpdateOne) SetExpiresAt(v time.Time) *WebSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *WebSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *WebSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WebSessionUpdateOne) SetCreatedAt(v time.Time) *WebSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WebSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *WebSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *WebSessionUpdateOne) SetLastSeenAt(v time.Time) *WebSessionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *WebSessionUpdateOne) SetUserID(id int) *WebSessionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *WebSessionUpdateOne) SetUser(v *User) *WebSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WebSessionMutation object of the builder.
func (_u *WebSessionUpdateOne) Mutation() *WebSessionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WebSessionUpdateOne) ClearUser() *WebSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the WebSessionUpdate builder.
func (_u *WebSessionUpdateOne) Where(ps ...predicate.WebSession) *WebSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebSessionUpdateOne) Select(field string, fields ...string) *WebSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebSession entity.
func (_u *WebSessionUpdateOne) Save(ctx context.Context) (*WebSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebSessionUpdateOne) SaveX(ctx context.Context) *WebSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		v := websession.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebSessionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebSession.user"`)
	}
	return nil
}

func (_u *WebSessionUpdateOne) sqlSave(ctx context.Context) (_node *WebSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(websession.Table, websession.Columns, sqlgraph.NewFieldSpec(websession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, websession.FieldID)
		for _, f := range fields {
			if !websession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != websession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(websession.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(websession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(websession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(websession.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   websession.UserTable,
			Columns: []string{websession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   websession.UserTable,
			Columns: []string{websession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{websession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
