// Code generated by ent, DO NOT EDIT.

package course

import (
	"langschool/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldName, v))
}

// TeacherName applies equality check predicate on the "teacher_name" field. It's identical to TeacherNameEQ.
func TeacherName(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTeacherName, v))
}

// TeacherID applies equality check predicate on the "teacher_id" field. It's identical to TeacherIDEQ.
func TeacherID(v int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTeacherID, v))
}

// LegacyLessonPrice applies equality check predicate on the "legacy_lesson_price" field. It's identical to LegacyLessonPriceEQ.
func LegacyLessonPrice(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLegacyLessonPrice, v))
}

// LegacySubscriptionPrice applies equality check predicate on the "legacy_subscription_price" field. It's identical to LegacySubscriptionPriceEQ.
func LegacySubscriptionPrice(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLegacySubscriptionPrice, v))
}

// LessonPriceCents applies equality check predicate on the "lesson_price_cents" field. It's identical to LessonPriceCentsEQ.
func LessonPriceCents(v int64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLessonPriceCents, v))
}

// SubscriptionPriceCents applies equality check predicate on the "subscription_price_cents" field. It's identical to SubscriptionPriceCentsEQ.
func SubscriptionPriceCents(v int64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldSubscriptionPriceCents, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldIsActive, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldName, v))
}

// TeacherNameEQ applies the EQ predicate on the "teacher_name" field.
func TeacherNameEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTeacherName, v))
}

// TeacherNameNEQ applies the NEQ predicate on the "teacher_name" field.
func TeacherNameNEQ(v string) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldTeacherName, v))
}

// TeacherNameIn applies the In predicate on the "teacher_name" field.
func TeacherNameIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldTeacherName, vs...))
}

// TeacherNameNotIn applies the NotIn predicate on the "teacher_name" field.
func TeacherNameNotIn(vs ...string) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldTeacherName, vs...))
}

// TeacherNameGT applies the GT predicate on the "teacher_name" field.
func TeacherNameGT(v string) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldTeacherName, v))
}

// TeacherNameGTE applies the GTE predicate on the "teacher_name" field.
func TeacherNameGTE(v string) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldTeacherName, v))
}

// TeacherNameLT applies the LT predicate on the "teacher_name" field.
func TeacherNameLT(v string) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldTeacherName, v))
}

// TeacherNameLTE applies the LTE predicate on the "teacher_name" field.
func TeacherNameLTE(v string) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldTeacherName, v))
}

// TeacherNameContains applies the Contains predicate on the "teacher_name" field.
func TeacherNameContains(v string) predicate.Course {
	return predicate.Course(sql.FieldContains(FieldTeacherName, v))
}

// TeacherNameHasPrefix applies the HasPrefix predicate on the "teacher_name" field.
func TeacherNameHasPrefix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasPrefix(FieldTeacherName, v))
}

// TeacherNameHasSuffix applies the HasSuffix predicate on the "teacher_name" field.
func TeacherNameHasSuffix(v string) predicate.Course {
	return predicate.Course(sql.FieldHasSuffix(FieldTeacherName, v))
}

// TeacherNameEqualFold applies the EqualFold predicate on the "teacher_name" field.
func TeacherNameEqualFold(v string) predicate.Course {
	return predicate.Course(sql.FieldEqualFold(FieldTeacherName, v))
}

// TeacherNameContainsFold applies the ContainsFold predicate on the "teacher_name" field.
func TeacherNameContainsFold(v string) predicate.Course {
	return predicate.Course(sql.FieldContainsFold(FieldTeacherName, v))
}

// TeacherIDEQ applies the EQ predicate on the "teacher_id" field.
func TeacherIDEQ(v int) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldTeacherID, v))
}

// TeacherIDNEQ applies the NEQ predicate on the "teacher_id" field.
func TeacherIDNEQ(v int) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldTeacherID, v))
}

// TeacherIDIn applies the In predicate on the "teacher_id" field.
func TeacherIDIn(vs ...int) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldTeacherID, vs...))
}

// TeacherIDNotIn applies the NotIn predicate on the "teacher_id" field.
func TeacherIDNotIn(vs ...int) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldTeacherID, vs...))
}

// TeacherIDIsNil applies the IsNil predicate on the "teacher_id" field.
func TeacherIDIsNil() predicate.Course {
	return predicate.Course(sql.FieldIsNull(FieldTeacherID))
}

// TeacherIDNotNil applies the NotNil predicate on the "teacher_id" field.
func TeacherIDNotNil() predicate.Course {
	return predicate.Course(sql.FieldNotNull(FieldTeacherID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldType, vs...))
}

// LegacyLessonPriceEQ applies the EQ predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLegacyLessonPrice, v))
}

// LegacyLessonPriceNEQ applies the NEQ predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceNEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldLegacyLessonPrice, v))
}

// LegacyLessonPriceIn applies the In predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldLegacyLessonPrice, vs...))
}

// LegacyLessonPriceNotIn applies the NotIn predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceNotIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldLegacyLessonPrice, vs...))
}

// LegacyLessonPriceGT applies the GT predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceGT(v float64) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldLegacyLessonPrice, v))
}

// LegacyLessonPriceGTE applies the GTE predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceGTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldLegacyLessonPrice, v))
}

// LegacyLessonPriceLT applies the LT predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceLT(v float64) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldLegacyLessonPrice, v))
}

// LegacyLessonPriceLTE applies the LTE predicate on the "legacy_lesson_price" field.
func LegacyLessonPriceLTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldLegacyLessonPrice, v))
}

// LegacySubscriptionPriceEQ applies the EQ predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLegacySubscriptionPrice, v))
}

// LegacySubscriptionPriceNEQ applies the NEQ predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceNEQ(v float64) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldLegacySubscriptionPrice, v))
}

// LegacySubscriptionPriceIn applies the In predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldLegacySubscriptionPrice, vs...))
}

// LegacySubscriptionPriceNotIn applies the NotIn predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceNotIn(vs ...float64) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldLegacySubscriptionPrice, vs...))
}

// LegacySubscriptionPriceGT applies the GT predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceGT(v float64) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldLegacySubscriptionPrice, v))
}

// LegacySubscriptionPriceGTE applies the GTE predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceGTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldLegacySubscriptionPrice, v))
}

// LegacySubscriptionPriceLT applies the LT predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceLT(v float64) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldLegacySubscriptionPrice, v))
}

// LegacySubscriptionPriceLTE applies the LTE predicate on the "legacy_subscription_price" field.
func LegacySubscriptionPriceLTE(v float64) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldLegacySubscriptionPrice, v))
}

// LessonPriceCentsEQ applies the EQ predicate on the "lesson_price_cents" field.
func LessonPriceCentsEQ(v int64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldLessonPriceCents, v))
}

// LessonPriceCentsNEQ applies the NEQ predicate on the "lesson_price_cents" field.
func LessonPriceCentsNEQ(v int64) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldLessonPriceCents, v))
}

// LessonPriceCentsIn applies the In predicate on the "lesson_price_cents" field.
func LessonPriceCentsIn(vs ...int64) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldLessonPriceCents, vs...))
}

// LessonPriceCentsNotIn applies the NotIn predicate on the "lesson_price_cents" field.
func LessonPriceCentsNotIn(vs ...int64) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldLessonPriceCents, vs...))
}

// LessonPriceCentsGT applies the GT predicate on the "lesson_price_cents" field.
func LessonPriceCentsGT(v int64) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldLessonPriceCents, v))
}

// LessonPriceCentsGTE applies the GTE predicate on the "lesson_price_cents" field.
func LessonPriceCentsGTE(v int64) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldLessonPriceCents, v))
}

// LessonPriceCentsLT applies the LT predicate on the "lesson_price_cents" field.
func LessonPriceCentsLT(v int64) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldLessonPriceCents, v))
}

// LessonPriceCentsLTE applies the LTE predicate on the "lesson_price_cents" field.
func LessonPriceCentsLTE(v int64) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldLessonPriceCents, v))
}

// SubscriptionPriceCentsEQ applies the EQ predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsEQ(v int64) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldSubscriptionPriceCents, v))
}

// SubscriptionPriceCentsNEQ applies the NEQ predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsNEQ(v int64) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldSubscriptionPriceCents, v))
}

// SubscriptionPriceCentsIn applies the In predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsIn(vs ...int64) predicate.Course {
	return predicate.Course(sql.FieldIn(FieldSubscriptionPriceCents, vs...))
}

// SubscriptionPriceCentsNotIn applies the NotIn predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsNotIn(vs ...int64) predicate.Course {
	return predicate.Course(sql.FieldNotIn(FieldSubscriptionPriceCents, vs...))
}

// SubscriptionPriceCentsGT applies the GT predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsGT(v int64) predicate.Course {
	return predicate.Course(sql.FieldGT(FieldSubscriptionPriceCents, v))
}

// SubscriptionPriceCentsGTE applies the GTE predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsGTE(v int64) predicate.Course {
	return predicate.Course(sql.FieldGTE(FieldSubscriptionPriceCents, v))
}

// SubscriptionPriceCentsLT applies the LT predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsLT(v int64) predicate.Course {
	return predicate.Course(sql.FieldLT(FieldSubscriptionPriceCents, v))
}

// SubscriptionPriceCentsLTE applies the LTE predicate on the "subscription_price_cents" field.
func SubscriptionPriceCentsLTE(v int64) predicate.Course {
	return predicate.Course(sql.FieldLTE(FieldSubscriptionPriceCents, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Course {
	return predicate.Course(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Course {
	return predicate.Course(sql.FieldNEQ(FieldIsActive, v))
}

// HasTeacher applies the HasEdge predicate on the "teacher" edge.
func HasTeacher() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeacherTable, TeacherColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeacherWith applies the HasEdge predicate on the "teacher" edge with a given conditions (other predicates).
func HasTeacherWith(preds ...predicate.Teacher) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newTeacherStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEnrollments applies the HasEdge predicate on the "enrollments" edge.
func HasEnrollments() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EnrollmentsTable, EnrollmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnrollmentsWith applies the HasEdge predicate on the "enrollments" edge with a given conditions (other predicates).
func HasEnrollmentsWith(preds ...predicate.Enrollment) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newEnrollmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMonthStats applies the HasEdge predicate on the "month_stats" edge.
func HasMonthStats() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MonthStatsTable, MonthStatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMonthStatsWith applies the HasEdge predicate on the "month_stats" edge with a given conditions (other predicates).
func HasMonthStatsWith(preds ...predicate.CourseMonthStat) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := newMonthStatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Course) predicate.Course {
	return predicate.Course(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Course) predicate.Course {
	return predicate.Course(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Course) predicate.Course {
	return predicate.Course(sql.NotPredicates(p))
}
