// Code generated by ent, DO NOT EDIT.

package coursemonthstat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the coursemonthstat type in the database.
	Label = "course_month_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCourseID holds the string denoting the course_id field in the database.
	FieldCourseID = "course_id"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldMonth holds the string denoting the month field in the database.
	FieldMonth = "month"
	// FieldSubscriptionLessonsHeld holds the string denoting the subscription_lessons_held field in the database.
	FieldSubscriptionLessonsHeld = "subscription_lessons_held"
	// EdgeCourse holds the string denoting the course edge name in mutations.
	EdgeCourse = "course"
	// Table holds the table name of the coursemonthstat in the database.
	Table = "course_month_stats"
	// CourseTable is the table that holds the course relation/edge.
	CourseTable = "course_month_stats"
	// CourseInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	CourseInverseTable = "courses"
	// CourseColumn is the table column denoting the course relation/edge.
	CourseColumn = "course_id"
)

// Columns holds all SQL columns for coursemonthstat fields.
var Columns = []string{
	FieldID,
	FieldCourseID,
	FieldYear,
	FieldMonth,
	FieldSubscriptionLessonsHeld,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSubscriptionLessonsHeld holds the default value on creation for the "subscription_lessons_held" field.
	DefaultSubscriptionLessonsHeld float64
)

// OrderOption defines the ordering options for the CourseMonthStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCourseID orders the results by the course_id field.
func ByCourseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCourseID, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByMonth orders the results by the month field.
func ByMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonth, opts...).ToFunc()
}

// BySubscriptionLessonsHeld orders the results by the subscription_lessons_held field.
func BySubscriptionLessonsHeld(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionLessonsHeld, opts...).ToFunc()
}

// ByCourseField orders the results by course field.
func ByCourseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCourseStep(), sql.OrderByField(field, opts...))
	}
}
func newCourseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CourseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
	)
}
