// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AttendanceMonth is the predicate function for attendancemonth builders.
type AttendanceMonth func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseMonthStat is the predicate function for coursemonthstat builders.
type CourseMonthStat func(*sql.Selector)

// Enrollment is the predicate function for enrollment builders.
type Enrollment func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// InvoiceLine is the predicate function for invoiceline builders.
type InvoiceLine func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WebSession is the predicate function for websession builders.
type WebSession func(*sql.Selector)
